import { Archive, CheckCircle2, Save } from "lucide-react";
import { getBankMonthClosures } from "@/lib/bank-data";
import { formatCurrency, formatDateOnly, formatMonthYear } from "@/lib/format";
import { closeBankMonth } from "./actions";

function currentMonth() { return new Intl.DateTimeFormat("en-CA", { timeZone:"America/Sao_Paulo", year:"numeric", month:"2-digit" }).format(new Date()); }

export default async function BankClosingPage({ searchParams }: { searchParams: Promise<{ salvo?: string; mes?: string }> }) {
  const params=await searchParams; const closures=await getBankMonthClosures(); const defaultMonth=(params.mes ?? `${currentMonth()}-01`).slice(0,7);
  return <section>
    <div className="page-header bank-page-header"><div><div className="eyebrow">Candinho Bank</div><h1>Fechamento Mensal</h1><p>Crie uma fotografia do seu financeiro ao final de cada mês para acompanhar evolução de saldo, estoque, recebíveis e dívidas.</p></div><span className="bank-module-badge"><Archive size={16}/>{closures.length} fechamento(s)</span></div>
    {params.salvo && <div className="bank-success-banner"><CheckCircle2 size={18}/><div><strong>Fechamento registrado.</strong><span>Se o mês já existia, a fotografia foi atualizada com os dados mais recentes.</span></div></div>}
    <article className="panel bank-close-month-panel"><div className="panel-head"><div><h2>Fechar ou atualizar um mês</h2><p>O sistema registra os números atuais como uma fotografia histórica. Você pode refazer o fechamento se precisar corrigir dados.</p></div></div>
      <form action={closeBankMonth}><div className="panel-body bank-charge-form-grid"><label className="field"><span>Mês de referência</span><input className="input" type="month" name="reference_month" defaultValue={defaultMonth} required/></label><label className="field bank-charge-form-wide"><span>Observações</span><textarea className="input bank-textarea" name="notes" placeholder="Ex.: mês com compra grande de estoque, viagem, investimento..."/></label></div><div className="bank-balance-update-actions"><button className="button gold" type="submit"><Save size={16}/>Registrar fechamento</button></div></form>
    </article>
    <div className="bank-annual-grid bank-closure-grid">{closures.map((item)=><article className="panel bank-annual-card" key={item.id}><div className="panel-body"><div className="bank-annual-card-head"><h2>{formatMonthYear(item.referenceMonth)}</h2><span className={`badge ${item.totalNetPosition<0?'red':'green'}`}>{formatCurrency(item.totalNetPosition)}</span></div><div className="bank-annual-lines"><div><span>Saldo em contas</span><strong>{formatCurrency(item.totalBalance)}</strong></div><div><span>Estoque Suplementos</span><strong>{formatCurrency(item.supplementsStockCost)}</strong></div><div><span>Estoque Fitness</span><strong>{formatCurrency(item.fitnessStockCost)}</strong></div><div><span>À receber Bank</span><strong>{formatCurrency(item.bankReceivables)}</strong></div><div><span>À receber operações</span><strong>{formatCurrency(item.operationReceivables)}</strong></div><div><span>Dívidas totais</span><strong>- {formatCurrency(item.totalDebtRemaining)}</strong></div><div><span>Posição operacional Company</span><strong>{formatCurrency(item.operationalNetPosition)}</strong></div><div className="total"><span>Posição líquida geral</span><strong>{formatCurrency(item.totalNetPosition)}</strong></div><div><span>Fechado em</span><strong>{formatDateOnly(item.closedOn)}</strong></div>{item.notes && <div><span>Observação</span><strong>{item.notes}</strong></div>}</div></div></article>)}{closures.length===0 && <article className="panel"><div className="empty"><strong>Nenhum fechamento ainda</strong>Faça o primeiro fechamento quando quiser guardar uma fotografia do seu financeiro.</div></article>}</div>
  </section>;
}
