import Link from "next/link";
import { AlertTriangle, Check, CircleDollarSign, Flag, HeartPulse, PiggyBank, Plane, Plus } from "lucide-react";
import { getBankFinancialGoals } from "@/lib/bank-financial-goals";
import { formatCurrency, formatDateOnly } from "@/lib/format";
import { createFinancialGoal, updateFinancialGoal } from "./actions";

const categoryLabel = { health: "Saúde", travel: "Viagem", purchase: "Compra", bill: "Conta", emergency: "Emergência", other: "Outro" };
function today() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Sao_Paulo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()); }

export default async function FinancialGoalsPage({ searchParams }: { searchParams: Promise<{ acao?: string; salvo?: string }> }) {
  const params = await searchParams;
  const goals = await getBankFinancialGoals();
  const active = goals.filter((goal) => goal.status === "active");
  const target = active.reduce((sum, goal) => sum + goal.targetAmount, 0);
  const reserved = active.reduce((sum, goal) => sum + goal.reservedAmount, 0);
  const urgent = active.filter((goal) => goal.priority === "urgent" || Boolean(goal.dueDate && goal.dueDate <= today()));
  return <section className="bank-goals-page">
    <div className="page-header bank-page-header"><div><div className="eyebrow">Candinho Bank · planejamento</div><h1>Pendências e objetivos</h1><p>Separe o dinheiro que precisa existir de uma compra de estoque. Aqui entram consulta, viagem, reserva, conta e qualquer valor com prazo.</p></div><Link className="button gold" href={params.acao === "nova" ? "/bank/objetivos" : "/bank/objetivos?acao=nova"}><Plus/>Nova pendência</Link></div>
    {params.salvo ? <div className="bank-success-banner"><Check/><div><strong>Pendência salva.</strong><span>O progresso e a urgência já foram recalculados.</span></div></div> : null}
    <div className="grid stats-grid bank-stats-grid"><article className="stat-card"><Flag/><span>Objetivos ativos</span><strong>{active.length}</strong><small>{urgent.length} urgente(s)</small></article><article className="stat-card"><CircleDollarSign/><span>Valor necessário</span><strong>{formatCurrency(target)}</strong><small>Total das metas abertas</small></article><article className="stat-card"><PiggyBank/><span>Já reservado</span><strong>{formatCurrency(reserved)}</strong><small>{target ? Math.min(100, Math.round(reserved / target * 100)) : 100}% do necessário</small></article><article className="stat-card"><AlertTriangle/><span>Ainda falta separar</span><strong>{formatCurrency(Math.max(target - reserved, 0))}</strong><small>Não significa déficit da empresa</small></article></div>
    {params.acao === "nova" ? <article className="panel bank-goal-create"><div className="panel-head"><div><h2>Nova pendência financeira</h2><p>Use “gasto” para algo que será pago e “reserva” para dinheiro que precisa ser juntado.</p></div></div><form action={createFinancialGoal} className="bank-goal-form"><label className="field wide"><span>Nome</span><input className="input" name="title" required placeholder="Ex.: Consulta da Júlia"/></label><label className="field"><span>Tipo</span><select className="input" name="goal_type"><option value="expense">Gasto com prazo</option><option value="reserve">Meta de reserva</option></select></label><label className="field"><span>Categoria</span><select className="input" name="category"><option value="health">Saúde</option><option value="travel">Viagem</option><option value="purchase">Compra</option><option value="bill">Conta</option><option value="emergency">Emergência</option><option value="other">Outro</option></select></label><label className="field"><span>Valor necessário</span><input className="input" name="target_amount" inputMode="decimal" required placeholder="400,00"/></label><label className="field"><span>Já reservado</span><input className="input" name="reserved_amount" inputMode="decimal" defaultValue="0"/></label><label className="field"><span>Prazo</span><input className="input" name="due_date" type="date"/></label><label className="field"><span>Prioridade</span><select className="input" name="priority"><option value="normal">Normal</option><option value="attention">Atenção</option><option value="urgent">Urgente</option></select></label><label className="field"><span>Forma obrigatória</span><input className="input" name="payment_method" placeholder="Ex.: Pix"/></label><label className="field"><span>Gasto mínimo previsto</span><input className="input" name="expected_spend_min" inputMode="decimal" placeholder="400,00"/></label><label className="field"><span>Gasto máximo previsto</span><input className="input" name="expected_spend_max" inputMode="decimal" placeholder="600,00"/></label><label className="field wide"><span>Observações</span><textarea className="input" name="notes" placeholder="Contexto importante para não esquecer."/></label><div className="bank-goal-actions wide"><Link className="button ghost" href="/bank/objetivos">Cancelar</Link><button className="button gold" type="submit">Salvar pendência</button></div></form></article> : null}
    <article className="panel"><div className="panel-head"><div><h2>O que precisa de dinheiro</h2><p>Urgência vem do prazo; progresso vem do valor já separado.</p></div></div><div className="bank-goal-list">{active.map((goal) => { const missing = Math.max(goal.targetAmount - goal.reservedAmount, 0); const pct = goal.targetAmount ? Math.min(100, goal.reservedAmount / goal.targetAmount * 100) : 0; const late = Boolean(goal.dueDate && goal.dueDate < today()); return <article className={`bank-goal-card ${late || goal.priority === "urgent" ? "urgent" : goal.priority}`} key={goal.id}><div className="bank-goal-icon">{goal.category === "travel" ? <Plane/> : goal.category === "health" ? <HeartPulse/> : <PiggyBank/>}</div><div><span>{categoryLabel[goal.category]} · {goal.goalType === "expense" ? "Gasto" : "Reserva"}</span><h2>{goal.title}</h2><p>{goal.notes || (goal.paymentMethod ? `Pagamento: ${goal.paymentMethod}` : "Sem observação")}</p><div className="bank-goal-progress"><i style={{ width: `${pct}%` }}/></div><small>{formatCurrency(goal.reservedAmount)} separado · faltam {formatCurrency(missing)}{goal.dueDate ? ` · até ${formatDateOnly(goal.dueDate)}` : " · sem prazo"}</small></div><form action={updateFinancialGoal}><input type="hidden" name="id" value={goal.id}/><input type="hidden" name="action" value="reserve"/><label><span>Valor separado</span><input className="input" name="reserved_amount" inputMode="decimal" defaultValue={goal.reservedAmount.toFixed(2).replace(".", ",")}/></label><button className="button ghost" type="submit">Atualizar</button></form><form action={updateFinancialGoal}><input type="hidden" name="id" value={goal.id}/><input type="hidden" name="action" value="complete"/><button className="button gold" type="submit"><Check/>Concluir</button></form></article>; })}{active.length === 0 ? <div className="bank-empty-state">Nenhuma pendência financeira aberta.</div> : null}</div></article>
  </section>;
}
