import Link from "next/link";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { ExternalLink, Gift, MegaphoneOff, MessageSquareQuote, TicketCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { getCurrentUserAccess } from "@/lib/data";

async function managerClient() { const access=await getCurrentUserAccess(); if(!access.canManageUsers) redirect("/company/inicio"); return createClient(); }
function refreshStorefront(){ revalidatePath("/company/vitrine"); revalidatePath("/catalogo"); }

async function createTestimonial(formData:FormData){"use server";const db=await managerClient();await db.from("storefront_testimonials").insert({customer_name:String(formData.get("name")||"").trim(),comment:String(formData.get("comment")||"").trim(),profession:String(formData.get("profession")||"").trim()||null,photo_url:String(formData.get("photo_url")||"").trim()||null,active:formData.get("active")==="on"});refreshStorefront();}
async function setTestimonialState(formData:FormData){"use server";const db=await managerClient();await db.from("storefront_testimonials").update({active:formData.get("active")==="true",updated_at:new Date().toISOString()}).eq("id",String(formData.get("id")));refreshStorefront();}
async function saveCampaign(formData:FormData){"use server";const db=await managerClient();await db.from("storefront_coupon_campaigns").update({name:String(formData.get("name")||"").trim(),discount_percent:Number(formData.get("discount_percent")||0),quota:Number(formData.get("quota")||0),active:formData.get("active")==="on",ends_at:String(formData.get("ends_at")||"").trim()||null}).eq("id",String(formData.get("id")));refreshStorefront();}
async function setCouponState(formData:FormData){"use server";const db=await managerClient();const status=String(formData.get("status"));await db.from("storefront_coupon_signups").update({status,used_at:status==="used"?new Date().toISOString():null}).eq("id",String(formData.get("id")));revalidatePath("/company/vitrine");}
async function revokeMarketingConsent(formData:FormData){"use server";const db=await managerClient();await db.from("storefront_coupon_signups").update({consent_email:false,consent_whatsapp:false,consent_sms:false}).eq("id",String(formData.get("id")));revalidatePath("/company/vitrine");}

export default async function CompanyStorefrontManagementPage(){
  const db=await managerClient();
  const[{data:testimonials},{data:coupons},{data:campaigns}]=await Promise.all([db.from("storefront_testimonials").select("*").order("created_at",{ascending:false}),db.from("storefront_coupon_signups").select("*").order("created_at",{ascending:false}),db.from("storefront_coupon_campaigns").select("*").order("starts_at",{ascending:false})]);
  const campaign=campaigns?.[0]??null;const active=(coupons??[]).filter(x=>x.status==="active").length;const used=(coupons??[]).filter(x=>x.status==="used").length;const authorized=(coupons??[]).filter(x=>x.consent_email||x.consent_whatsapp||x.consent_sms).length;
  return <div className="company-workspace-v2">
    <header className="company-workspace-head"><div><span>VITRINE · GESTÃO</span><h1>Clientes, depoimentos e cupons</h1><p>Controle a campanha pública e os consentimentos sem misturar esses cadastros com o CRM.</p></div><Link className="button ghost" href="/catalogo"><ExternalLink size={16}/>Abrir vitrine</Link></header>
    <section className="company-workspace-metrics"><article><Gift/><span>Cupons ativos</span><strong>{active}</strong></article><article><TicketCheck/><span>Cupons utilizados</span><strong>{used}</strong></article><article><MessageSquareQuote/><span>Depoimentos publicados</span><strong>{(testimonials??[]).filter(x=>x.active).length}</strong></article><article><MegaphoneOff/><span>Contatos autorizados</span><strong>{authorized}</strong></article></section>
    {campaign?<article className="panel"><div className="panel-head"><div><h2><Gift/> Campanha atual</h2><p>Confira primeiro; abra a edição somente quando quiser mudar alguma regra.</p></div><span className={`badge ${campaign.active?"green":"gray"}`}>{campaign.active?"Ativa":"Pausada"}</span></div><div className="company-campaign-readout"><div><span>Campanha</span><strong>{campaign.name}</strong></div><div><span>Desconto</span><strong>{campaign.discount_percent}%</strong></div><div><span>Vagas</span><strong>{campaign.quota}</strong></div><div><span>Validade</span><strong>{campaign.ends_at?new Date(campaign.ends_at).toLocaleDateString("pt-BR"):"Sem prazo"}</strong></div></div><details className="company-campaign-editor"><summary>Alterar campanha</summary><form action={saveCampaign} className="company-storefront-form"><input type="hidden" name="id" value={campaign.id}/><label><span>Nome da campanha</span><input name="name" defaultValue={campaign.name} required/></label><label><span>Percentual de desconto</span><input name="discount_percent" type="number" min="1" max="100" step="0.01" defaultValue={campaign.discount_percent} required/></label><label><span>Quantidade total de vagas</span><input name="quota" type="number" min="1" defaultValue={campaign.quota} required/></label><label><span>Data e hora para encerrar</span><input name="ends_at" type="datetime-local" defaultValue={campaign.ends_at?String(campaign.ends_at).slice(0,16):""}/></label><label className="company-checkbox-field"><input type="checkbox" name="active" defaultChecked={campaign.active}/> Campanha ativa</label><button className="button gold">Salvar alterações</button></form></details></article>:null}
    <article className="panel"><div className="panel-head"><div><h2><MessageSquareQuote/> Novo depoimento</h2><p>Publique somente relatos reais autorizados pelo cliente.</p></div></div><form action={createTestimonial} className="company-storefront-form"><label><span>Nome do cliente</span><input name="name" required/></label><label><span>Profissão ou função</span><input name="profession" placeholder="Opcional"/></label><label><span>Link da foto</span><input name="photo_url" placeholder="Opcional"/></label><label className="company-storefront-wide"><span>Comentário do cliente</span><textarea name="comment" required/></label><label className="company-checkbox-field"><input type="checkbox" name="active"/> Publicar agora</label><button className="button gold">Salvar depoimento</button></form><div className="company-storefront-list">{(testimonials??[]).map(item=><div key={item.id}><div><strong>{item.customer_name}</strong><p>{item.comment}</p></div><form action={setTestimonialState}><input type="hidden" name="id" value={item.id}/><input type="hidden" name="active" value={item.active?"false":"true"}/><button>{item.active?"Ocultar":"Publicar"}</button></form></div>)}</div></article>
    <article className="panel"><div className="panel-head"><div><h2><Gift/> Cupons da primeira compra</h2><p>O cupom e a autorização para mensagens são controles separados.</p></div><strong>{coupons?.length??0}</strong></div><div className="company-storefront-list">{(coupons??[]).map(item=>{const channels=[item.consent_whatsapp&&"WhatsApp",item.consent_email&&"e-mail",item.consent_sms&&"SMS"].filter(Boolean);return <div key={item.id}><div><strong>{item.customer_name} · {item.coupon_code}</strong><p>{item.email||item.phone} · Canais: {channels.join(", ")||"nenhum"} · {item.status}</p></div><div className="page-header-actions"><form action={setCouponState}><input type="hidden" name="id" value={item.id}/>{item.status!=="active"?<button name="status" value="active">Reativar</button>:null}{item.status!=="used"?<button name="status" value="used">Usado</button>:null}{item.status!=="cancelled"?<button name="status" value="cancelled">Cancelar cupom</button>:null}</form>{channels.length?<form action={revokeMarketingConsent}><input type="hidden" name="id" value={item.id}/><button title="Retirar autorizações de marketing"><MegaphoneOff size={14}/>Cancelar mensagens</button></form>:null}</div></div>})}</div></article>
  </div>;
}
