/* eslint-disable @next/next/no-img-element */
"use client";

import Link from "next/link";
import { ArrowRightLeft, Boxes, Building2, CircleDollarSign, Layers3, MapPin, PackageSearch, Percent, Plus, Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { formatCurrency } from "@/lib/format";
import type { ActivePromotionRow } from "@/lib/active-promotion-data";
import type { ProductComboRow } from "@/lib/types";

export type CompanyProductRow = {
  id: string; name: string; category: string; brand: string | null; image_url: string | null;
  sale_price: number; cost_price: number; physical_quantity: number; reserved_quantity: number; available_quantity: number;
  incoming_quantity: number; operation: "Suplementos" | "Fitness"; secondary_image_url?: string | null;
};

export type CompanyPartnerStockRow = {
  partnerId: string; partnerName: string; locationId: string; locationName: string; city: string | null;
  productId: string; productName: string; brand: string | null; category: string | null;
  imageUrl: string | null; costPrice: number; salePrice: number; quantity: number; updatedAt: string | null;
};

type Availability = "all" | "available" | "incoming" | "out";
type CatalogView = "all" | "Suplementos" | "Fitness" | "combos" | "promotions" | "partners";
function availabilityOf(product: CompanyProductRow): Exclude<Availability, "all"> { return product.available_quantity > 0 ? "available" : product.incoming_quantity > 0 ? "incoming" : "out"; }
function productHref(product: CompanyProductRow) { return product.operation === "Fitness" ? `/company/produtos/fitness/${product.id}` : `/company/produtos/${product.id}`; }

export function CompanyProductsWorkspace({ products, combos, promotions, partnerStock, initialView = "all" }: { products: CompanyProductRow[]; combos: ProductComboRow[]; promotions: ActivePromotionRow[]; partnerStock: CompanyPartnerStockRow[]; initialView?: CatalogView }) {
  const [query, setQuery] = useState("");
  const [view, setView] = useState<CatalogView>(initialView);
  const [availability, setAvailability] = useState<Availability>("all");
  const [category, setCategory] = useState("all");
  const [brand, setBrand] = useState("all");
  const [preview, setPreview] = useState<CompanyProductRow | null>(null);
  const [partnerId, setPartnerId] = useState("all");
  useEffect(() => { if (!preview) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setPreview(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [preview]);
  const operation = view === "Suplementos" || view === "Fitness" ? view : "all";
  const operationRows = useMemo(() => products.filter((product) => operation === "all" || product.operation === operation), [operation, products]);
  const categories = useMemo(() => [...new Set(operationRows.map((product) => product.category).filter(Boolean))].sort((a, b) => a.localeCompare(b, "pt-BR")), [operationRows]);
  const brands = useMemo(() => [...new Set(operationRows.map((product) => product.brand).filter((value): value is string => Boolean(value)))].sort((a, b) => a.localeCompare(b, "pt-BR")), [operationRows]);
  const visible = useMemo(() => products.filter((product) => {
    const needle = query.trim().toLocaleLowerCase("pt-BR");
    return (operation === "all" || product.operation === operation) && (availability === "all" || availabilityOf(product) === availability) && (category === "all" || product.category === category) && (brand === "all" || product.brand === brand) && (!needle || `${product.name} ${product.category} ${product.brand ?? ""}`.toLocaleLowerCase("pt-BR").includes(needle));
  }), [availability, brand, category, operation, products, query]);
  const metricRows = operationRows;
  const available = metricRows.filter((product) => product.available_quantity > 0);
  const selectView = (nextView: CatalogView) => { setView(nextView); setCategory("all"); setBrand("all"); setPartnerId("all"); };
  const visibleCombos = useMemo(() => combos.filter((combo) => !query.trim() || `${combo.name} ${combo.description ?? ""} ${combo.component_summary ?? ""}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))), [combos, query]);
  const visiblePromotions = useMemo(() => promotions.filter((item) => !query.trim() || `${item.promotion_name} ${item.item_label} ${item.category ?? ""}`.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR"))), [promotions, query]);
  const partners = useMemo(() => [...new Map(partnerStock.map((row) => [row.partnerId, { id: row.partnerId, name: row.partnerName }])).values()].sort((a, b) => a.name.localeCompare(b.name, "pt-BR")), [partnerStock]);
  const visiblePartnerStock = useMemo(() => partnerStock.filter((row) => {
    const needle = query.trim().toLocaleLowerCase("pt-BR");
    return (partnerId === "all" || row.partnerId === partnerId) && (!needle || `${row.productName} ${row.brand ?? ""} ${row.category ?? ""} ${row.partnerName} ${row.locationName}`.toLocaleLowerCase("pt-BR").includes(needle));
  }), [partnerId, partnerStock, query]);
  const partnerUnits = visiblePartnerStock.reduce((sum, row) => sum + row.quantity, 0);
  const activeCombos = combos.filter((combo) => combo.active);
  const activePromotions = promotions;
  const productCostByOperationId = new Map(products.map((product) => [`${product.operation}:${product.id}`, product.cost_price]));
  const promotedUnitCost = (item: ActivePromotionRow) => productCostByOperationId.get(`${item.operation_scope === "fitness" ? "Fitness" : "Suplementos"}:${item.operation_scope === "fitness" ? item.fitness_product_id : item.supplement_product_id}`) ?? 0;
  const productMetric = view === "combos" ? activeCombos.length : view === "promotions" ? activePromotions.length : view === "partners" ? new Set(visiblePartnerStock.map((row) => row.productId)).size : metricRows.length;
  const availableMetric = view === "combos" ? activeCombos.filter((combo) => combo.available_quantity > 0).length : view === "promotions" ? activePromotions.filter((item) => item.available_quantity > 0).length : view === "partners" ? new Set(visiblePartnerStock.filter((row) => row.quantity > 0).map((row) => row.productId)).size : available.length;
  const unitMetric = view === "combos" ? activeCombos.reduce((sum, combo) => sum + combo.available_quantity, 0) : view === "promotions" ? activePromotions.reduce((sum, item) => sum + item.available_quantity, 0) : view === "partners" ? partnerUnits : available.reduce((sum, product) => sum + product.available_quantity, 0);
  const costMetric = view === "combos" ? activeCombos.reduce((sum, combo) => sum + combo.available_quantity * combo.calculated_cost, 0) : view === "promotions" ? activePromotions.reduce((sum, item) => sum + item.available_quantity * promotedUnitCost(item), 0) : view === "partners" ? visiblePartnerStock.reduce((sum, row) => sum + row.quantity * row.costPrice, 0) : metricRows.reduce((sum, product) => sum + product.available_quantity * product.cost_price, 0);
  const primaryMetricLabel = view === "combos" ? "Combos ativos" : view === "promotions" ? "Produtos em promoção" : view === "partners" ? "Produtos nos parceiros" : "Produtos ativos";

  return <div className="company-workspace-v2">
    <header className="company-workspace-head"><div><span>COMPANY · CATÁLOGO INTERNO</span><h1>Produtos</h1><p>Clique na foto para ampliar; clique nos dados para abrir todas as informações.</p></div><div className="company-products-head-actions"><Link className="button ghost" href="/company/produtos/transferencias"><ArrowRightLeft size={16}/>Transferir</Link><Link className="button company-blue" href="/company/produtos/novo"><Plus size={16}/>Novo produto</Link></div></header>
    <section className="company-workspace-metrics company-product-metrics"><article><PackageSearch/><span>{primaryMetricLabel}</span><strong>{productMetric}</strong></article><article><Boxes/><span>Com disponibilidade</span><strong>{availableMetric}</strong></article><article><Boxes/><span>Saldo de estoque</span><strong>{unitMetric}</strong></article><article><CircleDollarSign/><span>Valor em estoque · custo</span><strong>{formatCurrency(costMetric)}</strong></article></section>
    <section className="company-workspace-panel"><div className="company-workspace-toolbar"><div><button className={view === "all" ? "active" : ""} onClick={() => selectView("all")}>Todas</button><button className={view === "Suplementos" ? "active" : ""} onClick={() => selectView("Suplementos")}>Suplementos</button><button className={view === "Fitness" ? "active" : ""} onClick={() => selectView("Fitness")}>Fitness</button><button className={view === "combos" ? "active" : ""} onClick={() => selectView("combos")}>Combos</button><button className={view === "promotions" ? "active" : ""} onClick={() => selectView("promotions")}>Promoções</button><button className={view === "partners" ? "active" : ""} onClick={() => selectView("partners")}>Parceiros</button></div><label><Search size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar produto, combo, promoção ou parceiro..."/></label></div>
      {view !== "combos" && view !== "promotions" && view !== "partners" ? <><div className="company-product-filters"><label><span>Disponibilidade</span><select value={availability} onChange={(event) => setAvailability(event.target.value as Availability)}><option value="all">Todas</option><option value="available">Com estoque</option><option value="incoming">Somente a caminho</option><option value="out">Zerados</option></select></label><label><span>Categoria</span><select value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">Todas as categorias</option>{categories.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label><span>Marca</span><select value={brand} onChange={(event) => setBrand(event.target.value)}><option value="all">Todas as marcas</option>{brands.map((item) => <option value={item} key={item}>{item}</option>)}</select></label>{(availability !== "all" || category !== "all" || brand !== "all" || query) ? <button type="button" onClick={() => { setQuery(""); setAvailability("all"); setCategory("all"); setBrand("all"); }}>Limpar filtros</button> : null}</div><p className="company-workspace-count">{visible.length} produto(s)</p>
      <div className="company-products-grid">{visible.map((product) => { const status = availabilityOf(product); return <article className={`company-product-card stock-${status} operation-${product.operation === "Fitness" ? "fitness" : "supplements"}`} key={`${product.operation}-${product.id}`}>
        <button type="button" className="company-product-card-visual" onClick={() => setPreview(product)} aria-label={`Ampliar foto de ${product.name}`}>{product.image_url ? <img src={product.image_url} alt={product.name}/> : <PackageSearch/>}<small>Ampliar</small></button>
        <Link href={productHref(product)}><span>{product.operation} · {product.category}{product.brand ? ` · ${product.brand}` : ""}</span><h2>{product.name}</h2><p><strong>{product.available_quantity}</strong> disponível · {product.reserved_quantity} reservado · {product.incoming_quantity} chegando</p><b>{formatCurrency(product.sale_price)}</b><small>Abrir informações →</small></Link>
      </article>; })}</div></> : null}
      {view === "combos" ? <><div className="company-catalog-view-head"><div><Layers3/><span><strong>Combos</strong><small>Ofertas montadas com estoque real dos componentes.</small></span></div><Link className="button company-blue" href="/company/produtos/combos/novo"><Plus size={15}/>Novo combo</Link></div><div className="company-products-grid company-combo-grid">{visibleCombos.map((combo) => <Link className={`company-catalog-special-card ${combo.available_quantity > 0 ? "available" : combo.incoming_quantity > 0 ? "incoming" : "out"}`} href={`/company/produtos/combos/${combo.id}/editar`} key={combo.id}>{combo.image_url ? <img src={combo.image_url} alt={combo.name}/> : <Layers3/>}<span><small>{combo.active ? "Ativo" : "Inativo"} · {combo.component_count} produto(s)</small><strong>{combo.name}</strong><p>{combo.component_summary ?? combo.description ?? "Configure os produtos deste combo."}</p><b>{formatCurrency(combo.sale_price)}</b><em>{combo.available_quantity} disponível · {combo.incoming_quantity} a caminho</em></span></Link>)}{visibleCombos.length === 0 ? <div className="company-empty-state"><Layers3/><strong>Nenhum combo encontrado</strong><span>Cadastre um combo ou altere a busca.</span></div> : null}</div></> : null}
      {view === "promotions" ? <><div className="company-catalog-view-head"><div><Percent/><span><strong>Promoções ativas</strong><small>Suplementos e Fitness reunidos na Company.</small></span></div></div><div className="company-products-grid company-promotion-grid">{visiblePromotions.map((item) => { const exhausted = item.available_quantity <= 0 && item.incoming_quantity <= 0; return <article className={`company-catalog-special-card ${item.available_quantity > 0 ? "available" : item.incoming_quantity > 0 ? "incoming" : "out"}`} key={item.promotion_item_id}>{item.image_url ? <img src={item.image_url} alt={item.item_label}/> : <Percent/>}<span><small>{item.operation_scope === "fitness" ? "Fitness" : "Suplementos"} · {item.promotion_name}</small><strong>{item.item_label}</strong><p>{item.effective_discount_pct.toLocaleString("pt-BR", { maximumFractionDigits: 1 })}% de desconto</p><b><s>{formatCurrency(item.current_price)}</s> {formatCurrency(item.effective_promotional_price)}</b><em className={exhausted ? "promotion-exhausted" : ""}>{exhausted ? "Promoção vigente · produto esgotado" : `${item.available_quantity} disponível · ${item.incoming_quantity} a caminho`}</em></span></article>; })}{visiblePromotions.length === 0 ? <div className="company-empty-state"><Percent/><strong>Nenhuma promoção ativa</strong><span>Quando uma promoção entrar em vigor, ela aparecerá aqui.</span></div> : null}</div></> : null}
      {view === "partners" ? <><div className="company-catalog-view-head"><div><Building2/><span><strong>Estoque nos parceiros</strong><small>Saldo físico fora dos estoques próprios da Company.</small></span></div></div><div className="company-partner-stock-tabs"><button className={partnerId === "all" ? "active" : ""} type="button" onClick={() => setPartnerId("all")}>Saldo total · {partnerStock.reduce((sum, row) => sum + row.quantity, 0)}</button>{partners.map((partner) => <button className={partnerId === partner.id ? "active" : ""} type="button" onClick={() => setPartnerId(partner.id)} key={partner.id}>{partner.name}</button>)}</div><p className="company-workspace-count">{visiblePartnerStock.length} produto(s) · {partnerUnits} unidade(s)</p><div className="company-products-grid company-partner-stock-grid">{visiblePartnerStock.map((row) => <article className="company-partner-stock-card" key={`${row.locationId}-${row.productId}`}>{row.imageUrl ? <img src={row.imageUrl} alt={row.productName}/> : <PackageSearch/>}<span><small><MapPin size={12}/>{row.partnerName}{row.city ? ` · ${row.city}` : ""}</small><strong>{row.productName}</strong><p>{[row.category, row.brand].filter(Boolean).join(" · ") || row.locationName}</p><b>{row.quantity} unidade(s)</b><em>{formatCurrency(row.salePrice)}</em></span></article>)}{visiblePartnerStock.length === 0 ? <div className="company-empty-state"><Building2/><strong>Nenhum saldo encontrado</strong><span>Este parceiro não possui produtos com saldo registrado.</span></div> : null}</div></> : null}
      {view === "promotions" ? <div className="company-promotion-create-shortcut"><Link className="button company-blue" href="/company/gestao/central/promocoes#nova-promocao"><Plus size={15}/>Adicionar promoção</Link></div> : null}
    </section>
    {preview ? <div className="company-product-click-preview" role="dialog" aria-modal="true" aria-label={`Fotos de ${preview.name}`} onClick={() => setPreview(null)}><article onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => setPreview(null)} aria-label="Fechar"><X/></button><header><span>{preview.operation}</span><strong>{preview.name}</strong></header><div className={preview.secondary_image_url ? "has-secondary" : ""}>{preview.image_url ? <figure><img src={preview.image_url} alt={preview.name}/><figcaption>Produto</figcaption></figure> : null}{preview.secondary_image_url ? <figure><img src={preview.secondary_image_url} alt={`Tabela nutricional de ${preview.name}`}/><figcaption>Tabela nutricional</figcaption></figure> : null}</div></article></div> : null}
  </div>;
}
