"use client";
import { LoaderCircle, Plus, Save, Trash2 } from "lucide-react";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { formatCurrency } from "@/lib/format";
import type { FitnessCustomerRow,FitnessStockRow } from "@/lib/types";

type Draft={key:string;variantId:string;quantity:string;unitPrice:string};
const key=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)};

export function FitnessConsignmentForm({stock,customers,responsible}:{stock:FitnessStockRow[];customers:FitnessCustomerRow[];responsible:string}){
 const router=useRouter();
 const options=useMemo(()=>stock.filter(r=>r.product_active&&r.variant_active&&r.available_quantity>0).sort((a,b)=>`${a.product_name}${a.size}${a.color}`.localeCompare(`${b.product_name}${b.size}${b.color}`,"pt-BR")),[stock]);
 const[customerId,setCustomerId]=useState("");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[instagram,setInstagram]=useState("");const[city,setCity]=useState("");const[source,setSource]=useState("");
 const[startedOn,setStartedOn]=useState(day());const[expected,setExpected]=useState(day(3));const[items,setItems]=useState<Draft[]>([{key:key(),variantId:"",quantity:"1",unitPrice:""}]);const[notes,setNotes]=useState("");const[loading,setLoading]=useState(false);const[message,setMessage]=useState<string|null>(null);
 const rowFor=(id:string)=>options.find(r=>r.variant_id===id);const update=(k:string,c:Partial<Draft>)=>setItems(v=>v.map(i=>i.key===k?{...i,...c}:i));
 function chooseCustomer(id:string){setCustomerId(id);const c=customers.find(x=>x.id===id);if(c){setName(c.name);setPhone(c.phone??"");setInstagram(c.instagram??"");setCity(c.city??"");setSource(c.source??"")}}
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage(null);try{if(!name.trim())throw new Error("Informe a cliente.");if(items.some(i=>!i.variantId||Number(i.quantity)<=0))throw new Error("Revise as peças enviadas para prova.");for(const i of items){const r=rowFor(i.variantId);if(r&&Number(i.quantity)>r.available_quantity)throw new Error(`${r.product_name} · ${r.size} · ${r.color}: disponível ${r.available_quantity}.`)}const{data,error}=await createClient().rpc("create_fitness_consignment",{p_customer_id:customerId||null,p_customer_name:name.trim(),p_customer_phone:phone.trim()||null,p_customer_instagram:instagram.trim()||null,p_city:city.trim()||null,p_customer_source:source.trim()||null,p_started_on:startedOn,p_expected_return_on:expected||null,p_items:items.map(i=>({variant_id:i.variantId,quantity:Number(i.quantity),unit_price:Number(i.unitPrice||rowFor(i.variantId)?.sale_price||0)})),p_responsible:responsible,p_notes:notes.trim()||null});if(error)throw error;router.push(`/fitness/consignacoes/${String(data)}`);router.refresh()}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível gerar a consignação.")}finally{setLoading(false)}}
 return <form className="new-sale-layout" onSubmit={submit}><div className="new-sale-main">
  <article className="panel"><div className="panel-head"><div><h2>Cliente</h2><p>Quem está levando as peças para experimentar.</p></div></div><div className="panel-body form-grid-two">
   <label className="field field-span-two"><span>Cliente existente</span><select className="select" value={customerId} onChange={e=>chooseCustomer(e.target.value)}><option value="">Nova cliente</option>{customers.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}{c.city?` · ${c.city}`:""}</option>)}</select></label>
   <label className="field"><span>Nome</span><input className="input" required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Telefone</span><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></label>
   <label className="field"><span>Instagram</span><input className="input" value={instagram} onChange={e=>setInstagram(e.target.value)}/></label><label className="field"><span>Cidade</span><input className="input" value={city} onChange={e=>setCity(e.target.value)}/></label>
   <label className="field"><span>Data de saída</span><input className="input" type="date" value={startedOn} onChange={e=>setStartedOn(e.target.value)}/></label><label className="field"><span>Previsão de acerto</span><input className="input" type="date" value={expected} onChange={e=>setExpected(e.target.value)}/></label>
  </div></article>
  <article className="panel"><div className="panel-head"><div><h2>Peças em prova</h2><p>Enquanto estiverem com a cliente, deixam de aparecer como disponíveis.</p></div><button type="button" className="button ghost" onClick={()=>setItems(v=>[...v,{key:key(),variantId:"",quantity:"1",unitPrice:""}])}><Plus size={16}/>Adicionar</button></div><div className="panel-body sale-form-items">{items.map((item,index)=>{const r=rowFor(item.variantId);return <div className="sale-form-item" key={item.key}><div className="sale-form-item-head"><strong>Peça {index+1}</strong>{items.length>1&&<button type="button" className="icon-button" onClick={()=>setItems(v=>v.filter(x=>x.key!==item.key))}><Trash2 size={16}/></button>}</div><div className="sale-form-item-grid"><label className="field sale-product-field"><span>Produto · tamanho · cor</span><select className="select" value={item.variantId} onChange={e=>{const x=rowFor(e.target.value);update(item.key,{variantId:e.target.value,unitPrice:x?String(x.sale_price):""})}}><option value="">Selecione</option>{options.map(o=><option key={o.variant_id} value={o.variant_id}>{o.product_name} · {o.size} · {o.color} · disp. {o.available_quantity}</option>)}</select></label><label className="field"><span>Qtd.</span><input className="input" type="number" min="1" max={r?.available_quantity} value={item.quantity} onChange={e=>update(item.key,{quantity:e.target.value})}/></label><label className="field"><span>Preço se ficar</span><input className="input" type="number" min="0" step="0.01" value={item.unitPrice} onChange={e=>update(item.key,{unitPrice:e.target.value})}/></label></div>{r&&<div className="sale-stock-strip"><span>Disponível <strong>{r.available_quantity}</strong></span><span>Reservado <strong>{r.reserved_quantity}</strong></span><span>Preço <strong>{formatCurrency(r.sale_price)}</strong></span></div>}</div>})}</div></article>
  <article className="panel"><div className="panel-head"><div><h2>Observações</h2></div></div><div className="panel-body"><textarea className="textarea" rows={4} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Ex.: levou para provar em casa; combinar retorno na sexta."/></div></article>
 </div><aside className="new-sale-side"><article className="panel product-editor-summary"><div className="panel-body"><p>Ao salvar, as peças continuam no estoque físico, mas ficam marcadas como <strong>em prova</strong> e não podem ser prometidas para outra cliente.</p>{message&&<p className="form-error visible">{message}</p>}<button className="button gold product-save-button" disabled={loading}>{loading?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>}Gerar consignação</button></div></article></aside>
 </form>
}
