"use client";

import { LoaderCircle, Plus, Save, Trash2 } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { FitnessProductRow, FitnessStockRow } from "@/lib/types";

type VariantDraft={id:string|null;key:string;size:string;color:string;sku:string;costPrice:string;salePrice:string;active:boolean};
const makeKey=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;

export function FitnessProductForm({product,variants}:{product?:FitnessProductRow;variants?:FitnessStockRow[]}){
 const router=useRouter();
 const [name,setName]=useState(product?.name??"");const [category,setCategory]=useState(product?.category??"Vestuário");const [description,setDescription]=useState(product?.description??"");const [imageUrl,setImageUrl]=useState(product?.image_url??"");const [active,setActive]=useState(product?.active??true);
 const [rows,setRows]=useState<VariantDraft[]>(variants?.length?variants.map((v)=>({id:v.variant_id,key:v.variant_id,size:v.size,color:v.color,sku:v.sku??"",costPrice:String(v.cost_price),salePrice:String(v.sale_price),active:v.variant_active})):[{id:null,key:makeKey(),size:"P",color:"Preto",sku:"",costPrice:"0",salePrice:"0",active:true}]);
 const [loading,setLoading]=useState(false);const [message,setMessage]=useState<string|null>(null);
 const update=(key:string,change:Partial<VariantDraft>)=>setRows((current)=>current.map((row)=>row.key===key?{...row,...change}:row));
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage(null);try{if(!name.trim())throw new Error("Informe o nome da peça.");if(rows.some((row)=>!row.size.trim()||!row.color.trim()||Number(row.costPrice)<0||Number(row.salePrice)<0))throw new Error("Revise as variações.");const {data,error}=await createClient().rpc("save_fitness_product",{p_product_id:product?.id??null,p_name:name.trim(),p_category:category.trim(),p_description:description.trim()||null,p_image_url:imageUrl.trim()||null,p_active:active,p_variants:rows.map((row)=>({id:row.id,size:row.size.trim(),color:row.color.trim(),sku:row.sku.trim()||null,cost_price:Number(row.costPrice),sale_price:Number(row.salePrice),active:row.active}))});if(error)throw error;router.push(`/fitness/produtos/${String(data)}`);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar a peça.");}finally{setLoading(false);}}
 return <form className="product-editor-layout" onSubmit={submit}><div className="product-editor-main">
  <article className="panel"><div className="panel-head"><div><h2>Peça</h2><p>Modelo principal usado no catálogo e no estoque.</p></div></div><div className="panel-body form-grid-two"><label className="field field-span-two"><span>Nome</span><input className="input" required value={name} onChange={(e)=>setName(e.target.value)}/></label><label className="field"><span>Categoria</span><input className="input" value={category} onChange={(e)=>setCategory(e.target.value)}/></label><label className="field"><span>URL da foto</span><input className="input" value={imageUrl} onChange={(e)=>setImageUrl(e.target.value)}/></label><label className="field field-span-two"><span>Descrição</span><textarea className="textarea" rows={3} value={description} onChange={(e)=>setDescription(e.target.value)}/></label></div></article>
  <article className="panel"><div className="panel-head"><div><h2>Variações</h2><p>Tamanho, cor, custo e preço de venda.</p></div><button type="button" className="button ghost" onClick={()=>setRows((current)=>[...current,{id:null,key:makeKey(),size:"P",color:"Preto",sku:"",costPrice:"0",salePrice:"0",active:true}])}><Plus size={16}/>Adicionar</button></div><div className="panel-body sale-form-items">{rows.map((row,index)=><div className="sale-form-item" key={row.key}><div className="sale-form-item-head"><strong>Variação {index+1}</strong>{rows.length>1&&!row.id&&<button type="button" className="icon-button" onClick={()=>setRows((current)=>current.filter((item)=>item.key!==row.key))}><Trash2 size={16}/></button>}</div><div className="form-grid-three"><label className="field"><span>Tamanho</span><input className="input" value={row.size} onChange={(e)=>update(row.key,{size:e.target.value})}/></label><label className="field"><span>Cor</span><input className="input" value={row.color} onChange={(e)=>update(row.key,{color:e.target.value})}/></label><label className="field"><span>SKU</span><input className="input" value={row.sku} onChange={(e)=>update(row.key,{sku:e.target.value})}/></label><label className="field"><span>Custo</span><input className="input" type="number" min="0" step="0.01" value={row.costPrice} onChange={(e)=>update(row.key,{costPrice:e.target.value})}/></label><label className="field"><span>Venda</span><input className="input" type="number" min="0" step="0.01" value={row.salePrice} onChange={(e)=>update(row.key,{salePrice:e.target.value})}/></label><label className="switch-row"><div><strong>Ativa</strong></div><input type="checkbox" checked={row.active} onChange={(e)=>update(row.key,{active:e.target.checked})}/></label></div></div>)}</div></article>
 </div><aside className="product-editor-side"><article className="panel"><div className="panel-body product-switch-list"><label className="switch-row"><div><strong>Peça ativa</strong><span>Disponível para pedidos e vendas.</span></div><input type="checkbox" checked={active} onChange={(e)=>setActive(e.target.checked)}/></label></div></article><article className="panel"><div className="panel-body">{message&&<p className="form-error visible">{message}</p>}<button className="button gold product-save-button" disabled={loading}>{loading?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>}Salvar peça</button></div></article></aside></form>;
}
