"use client";
import { LoaderCircle,Plus,Save,Trash2 } from "lucide-react";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { formatCurrency } from "@/lib/format";
import type { FitnessCustomerRow,FitnessStockRow } from "@/lib/types";

type Draft={key:string;variantId:string;quantity:string;unitPrice:string};
const key=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)};

export function FitnessQuoteForm({stock,customers,responsible}:{stock:FitnessStockRow[];customers:FitnessCustomerRow[];responsible:string}){
 const router=useRouter();const options=useMemo(()=>stock.filter(r=>r.product_active&&r.variant_active).sort((a,b)=>`${a.product_name}${a.size}${a.color}`.localeCompare(`${b.product_name}${b.size}${b.color}`,"pt-BR")),[stock]);
 const[customerId,setCustomerId]=useState("");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[instagram,setInstagram]=useState("");const[city,setCity]=useState("");const[source,setSource]=useState("");
 const[quotedOn,setQuotedOn]=useState(day());const[validUntil,setValidUntil]=useState(day(7));const[discount,setDiscount]=useState("0");const[notes,setNotes]=useState("");const[items,setItems]=useState<Draft[]>([{key:key(),variantId:"",quantity:"1",unitPrice:""}]);const[loading,setLoading]=useState(false);const[message,setMessage]=useState<string|null>(null);
 const rowFor=(id:string)=>options.find(r=>r.variant_id===id);const update=(k:string,c:Partial<Draft>)=>setItems(v=>v.map(i=>i.key===k?{...i,...c}:i));const gross=items.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.unitPrice)||0),0);const total=Math.max(gross-(Number(discount)||0),0);
 function chooseCustomer(id:string){setCustomerId(id);const c=customers.find(x=>x.id===id);if(c){setName(c.name);setPhone(c.phone??"");setInstagram(c.instagram??"");setCity(c.city??"");setSource(c.source??"")}}
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage(null);try{if(!name.trim())throw new Error("Informe a cliente.");if(items.some(i=>!i.variantId||Number(i.quantity)<=0||Number(i.unitPrice)<0))throw new Error("Revise os itens do orçamento.");const{data,error}=await createClient().rpc("save_fitness_quote",{p_quote_id:null,p_customer_id:customerId||null,p_customer_name:name.trim(),p_customer_phone:phone.trim()||null,p_customer_instagram:instagram.trim()||null,p_city:city.trim()||null,p_customer_source:source.trim()||null,p_quoted_on:quotedOn,p_valid_until:validUntil,p_items:items.map(i=>({variant_id:i.variantId,quantity:Number(i.quantity),unit_price:Number(i.unitPrice)})),p_discount_amount:Number(discount)||0,p_responsible:responsible,p_notes:notes.trim()||null});if(error)throw error;router.push(`/fitness/orcamentos/${String(data)}`);router.refresh()}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível salvar o orçamento.")}finally{setLoading(false)}}
 return <form className="new-sale-layout" onSubmit={submit}><div className="new-sale-main">
  <article className="panel"><div className="panel-head"><div><h2>Cliente</h2><p>Selecione um cliente existente ou cadastre automaticamente.</p></div></div><div className="panel-body form-grid-two"><label className="field field-span-two"><span>Cliente existente</span><select className="select" value={customerId} onChange={e=>chooseCustomer(e.target.value)}><option value="">Novo cliente</option>{customers.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.name}{c.city?` · ${c.city}`:""}</option>)}</select></label><label className="field"><span>Nome</span><input className="input" required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Telefone</span><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="field"><span>Instagram</span><input className="input" value={instagram} onChange={e=>setInstagram(e.target.value)}/></label><label className="field"><span>Cidade</span><input className="input" value={city} onChange={e=>setCity(e.target.value)}/></label></div></article>
  <article className="panel"><div className="panel-head"><div><h2>Itens da proposta</h2><p>O orçamento não reserva estoque. A disponibilidade é validada ao converter em venda.</p></div><button type="button" className="button ghost" onClick={()=>setItems(v=>[...v,{key:key(),variantId:"",quantity:"1",unitPrice:""}])}><Plus size={16}/>Adicionar</button></div><div className="panel-body sale-form-items">{items.map((item,index)=>{const r=rowFor(item.variantId);return <div className="sale-form-item" key={item.key}><div className="sale-form-item-head"><strong>Item {index+1}</strong>{items.length>1&&<button type="button" className="icon-button" onClick={()=>setItems(v=>v.filter(x=>x.key!==item.key))}><Trash2 size={16}/></button>}</div><div className="sale-form-item-grid"><label className="field sale-product-field"><span>Produto</span><select className="select" value={item.variantId} onChange={e=>{const r=rowFor(e.target.value);update(item.key,{variantId:e.target.value,unitPrice:r?String(r.sale_price):""})}}><option value="">Selecione</option>{options.map(o=><option key={o.variant_id} value={o.variant_id}>{o.product_name} · {o.size} · {o.color}</option>)}</select></label><label className="field"><span>Qtd.</span><input className="input" type="number" min="1" value={item.quantity} onChange={e=>update(item.key,{quantity:e.target.value})}/></label><label className="field"><span>Preço</span><input className="input" type="number" min="0" step="0.01" value={item.unitPrice} onChange={e=>update(item.key,{unitPrice:e.target.value})}/></label></div>{r&&<div className="sale-stock-strip"><span>Disponível <strong>{r.available_quantity}</strong></span><span>A caminho <strong>{r.incoming_quantity}</strong></span><span>Padrão <strong>{formatCurrency(r.sale_price)}</strong></span></div>}</div>})}</div></article>
  <article className="panel"><div className="panel-head"><div><h2>Observações</h2></div></div><div className="panel-body"><textarea className="textarea" rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></div></article>
 </div><aside className="new-sale-side"><article className="panel"><div className="panel-head"><div><h2>Validade</h2></div></div><div className="panel-body product-switch-list"><label className="field"><span>Data</span><input className="input" type="date" value={quotedOn} onChange={e=>setQuotedOn(e.target.value)}/></label><label className="field"><span>Válido até</span><input className="input" type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><label className="field"><span>Desconto</span><input className="input" type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)}/></label></div></article><article className="panel product-editor-summary"><div className="panel-body"><dl><div><dt>Subtotal</dt><dd>{formatCurrency(gross)}</dd></div><div><dt>Total</dt><dd>{formatCurrency(total)}</dd></div></dl>{message&&<p className="form-error visible">{message}</p>}<button className="button gold product-save-button" disabled={loading}>{loading?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>}Salvar orçamento</button></div></article></aside>
 </form>
}
