"use client";
import { LoaderCircle,ShoppingBag,XCircle } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export function FitnessQuoteConvertForm({id}:{id:string}){
 const router=useRouter();const[mode,setMode]=useState("receivable");const[paidOn,setPaidOn]=useState(today());const[method,setMethod]=useState("Pix");const[dueOn,setDueOn]=useState(today());const[delivered,setDelivered]=useState(false);const[deliveredOn,setDeliveredOn]=useState(today());const[notes,setNotes]=useState("");const[loading,setLoading]=useState(false);const[message,setMessage]=useState<string|null>(null);
 async function convert(){setLoading(true);setMessage(null);try{const{data,error}=await createClient().rpc("convert_fitness_quote_to_sale",{p_quote_id:id,p_payment_mode:mode,p_paid_on:mode==="paid"?paidOn:null,p_payment_method:mode==="paid"?method:null,p_payment_due_on:mode==="combined"?dueOn:null,p_delivered:delivered,p_delivered_on:delivered?deliveredOn:null,p_notes:notes.trim()||null});if(error)throw error;router.push(`/fitness/vendas/${String(data)}`);router.refresh()}catch(err){setMessage(err instanceof Error?err.message:"Não foi possível converter o orçamento.")}finally{setLoading(false)}}
 async function close(status:"lost"|"cancelled"){setLoading(true);const{error}=await createClient().rpc("update_fitness_quote_status",{p_quote_id:id,p_status:status,p_notes:status==="lost"?"Cliente não fechou o orçamento":"Orçamento cancelado"});if(error){setMessage(error.message);setLoading(false);return}router.push("/fitness/orcamentos");router.refresh()}
 return <article className="panel"><div className="panel-head"><div><h2>Converter em venda</h2><p>A disponibilidade real é validada agora. Se a peça estiver em prova com outra cliente, a conversão será bloqueada.</p></div></div><div className="panel-body form-grid-two"><label className="field"><span>Pagamento</span><select className="select" value={mode} onChange={e=>setMode(e.target.value)}><option value="receivable">A receber</option><option value="paid">Pago</option><option value="combined">Pagamento combinado</option></select></label>{mode==="paid"&&<><label className="field"><span>Data</span><input className="input" type="date" value={paidOn} onChange={e=>setPaidOn(e.target.value)}/></label><label className="field"><span>Forma</span><select className="select" value={method} onChange={e=>setMethod(e.target.value)}>{["Pix","Dinheiro","Cartão","Link de Pagamento","Pagamento fracionado"].map(x=><option key={x}>{x}</option>)}</select></label></>}{mode==="combined"&&<label className="field"><span>Data combinada</span><input className="input" type="date" value={dueOn} onChange={e=>setDueOn(e.target.value)}/></label>}<label className="switch-row"><div><strong>Entregar agora</strong><span>Baixa o estoque imediatamente.</span></div><input type="checkbox" checked={delivered} onChange={e=>setDelivered(e.target.checked)}/></label>{delivered&&<label className="field"><span>Data da entrega</span><input className="input" type="date" value={deliveredOn} onChange={e=>setDeliveredOn(e.target.value)}/></label>}<label className="field field-span-two"><span>Observações</span><textarea className="textarea" rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{message&&<p className="form-error visible">{message}</p>}<div className="panel-actions"><button type="button" className="button gold" disabled={loading} onClick={convert}>{loading?<LoaderCircle className="spin" size={16}/>:<ShoppingBag size={16}/>}Converter em venda</button><button type="button" className="button ghost" disabled={loading} onClick={()=>close("lost")}><XCircle size={16}/>Marcar como perdido</button><button type="button" className="button ghost" disabled={loading} onClick={()=>close("cancelled")}>Cancelar orçamento</button></div></article>
}
