"use client";
import Link from "next/link";
import { LoaderCircle, Save, UserRoundPlus } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
export function NewCustomerForm(){const router=useRouter();const[name,setName]=useState("");const[phone,setPhone]=useState("");const[city,setCity]=useState("");const[reference,setReference]=useState("");const[notes,setNotes]=useState("");const[loading,setLoading]=useState(false);const[message,setMessage]=useState<string|null>(null);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage(null);try{const supabase=createClient();const{data,error}=await supabase.rpc("create_customer",{p_name:name.trim(),p_phone:phone.trim()||null,p_city:city.trim()||null,p_reference:reference.trim()||null,p_notes:notes.trim()||null});if(error)throw error;router.push(`/clientes/${String(data)}`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível cadastrar o cliente.");}finally{setLoading(false);}}
return <form className="panel compact-form-panel" onSubmit={submit}><div className="panel-head"><div><h2>Dados do cliente</h2><p>Cadastre apenas o necessário.</p></div><UserRoundPlus size={20}/></div><div className="panel-body form-grid-two"><label className="field field-span-two"><span>Nome</span><input className="input" required value={name} onChange={e=>setName(e.target.value)}/></label><label className="field"><span>Telefone</span><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label className="field"><span>Cidade</span><input className="input" value={city} onChange={e=>setCity(e.target.value)}/></label><label className="field field-span-two"><span>Referência</span><input className="input" value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field field-span-two"><span>Observações</span><textarea className="textarea" rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div><div className="form-footer"><Link className="button ghost" href="/clientes">Cancelar</Link><button className="button gold" disabled={loading}>{loading?<LoaderCircle className="spin" size={17}/>:<Save size={17}/>} {loading?"Salvando":"Salvar cliente"}</button></div>{message&&<p className="form-message">{message}</p>}</form>}
