"use client";
import { Check,Clipboard,LoaderCircle,MessageSquareText,RefreshCcw,Send } from "lucide-react";
import { useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Sao_Paulo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export function PostSaleNexusCard({batchId,phone,initialMessage,initialMeta,status,dueOn}:{batchId:string;phone:string|null;initialMessage:string|null;initialMeta:any;status:string;dueOn:string}){
 const router=useRouter();const[message,setMessage]=useState(initialMessage??"");const[meta,setMeta]=useState<any>(initialMeta??{});const[loading,setLoading]=useState(false);const[feedback,setFeedback]=useState<string|null>(null);const[newDue,setNewDue]=useState(dueOn);const[outcome,setOutcome]=useState("Cliente respondeu bem ao pós-venda");const[notes,setNotes]=useState("");
 const wa=useMemo(()=>{const digits=(phone??"").replace(/\D/g,"");if(!digits||!message)return null;const full=digits.startsWith("55")?digits:`55${digits}`;return `https://wa.me/${full}?text=${encodeURIComponent(message)}`},[phone,message]);
 async function generate(){setLoading(true);setFeedback(null);try{const{data,error}=await createClient().functions.invoke("post-sale-nexus-suggest",{body:{batch_id:batchId}});if(error)throw error;if(data?.error)throw new Error(data.error);setMessage(data.message??"");setMeta(data);setFeedback("Mensagem atualizada pelo Nexus.")}catch(err){setFeedback(err instanceof Error?err.message:"Não foi possível gerar a mensagem.")}finally{setLoading(false)}}
 async function copy(){await navigator.clipboard.writeText(message);setFeedback("Mensagem copiada.")}
 async function reschedule(){setLoading(true);setFeedback(null);try{const due=`${newDue}T12:00:00-03:00`;const{error}=await createClient().rpc("reschedule_operational_event",{p_source_type:"sale_post_sale",p_source_id:batchId,p_due_at:due});if(error)throw error;setFeedback("Pós-venda reagendado.");router.refresh()}catch(err){setFeedback(err instanceof Error?err.message:"Não foi possível reagendar.")}finally{setLoading(false)}}
 async function complete(){setLoading(true);setFeedback(null);try{const{error}=await createClient().rpc("complete_operational_event",{p_source_type:"sale_post_sale",p_source_id:batchId,p_completed_on:today(),p_outcome:outcome.trim()||null,p_notes:notes.trim()||null,p_payment_method:null});if(error)throw error;router.push("/pos-venda?concluido=1");router.refresh()}catch(err){setFeedback(err instanceof Error?err.message:"Não foi possível concluir.")}finally{setLoading(false)}}
 return <div style={{display:"grid",gap:16}}>
  <article className="panel"><div className="panel-head"><div><h2><MessageSquareText size={18}/> Nexus IA · mensagem de pós-venda</h2><p>O Nexus considera as compras agrupadas, histórico, leads, interações e observações do cliente.</p></div><button type="button" className="button gold" disabled={loading} onClick={generate}>{loading?<LoaderCircle className="spin" size={16}/>:<RefreshCcw size={16}/>} {message?"Regenerar mensagem":"Gerar mensagem"}</button></div><div className="panel-body">
   {message?<><textarea className="textarea" rows={7} value={message} onChange={e=>setMessage(e.target.value)}/><div className="panel-actions"><button type="button" className="button ghost" onClick={copy}><Clipboard size={16}/>Copiar</button>{wa&&<a className="button gold" href={wa} target="_blank" rel="noreferrer"><Send size={16}/>Abrir no WhatsApp</a>}</div>{meta?.context_summary&&<p><strong>Leitura do Nexus:</strong> {meta.context_summary}</p>}{meta?.suggested_action&&<p><strong>Próxima ação sugerida:</strong> {meta.suggested_action}</p>}{Array.isArray(meta?.warnings)&&meta.warnings.length>0&&<p><strong>Atenção:</strong> {meta.warnings.join(" · ")}</p>}</>:<p>Gere a mensagem para não precisar montar o contexto manualmente ou mandar prints para outro chat.</p>}
   {feedback&&<p className="form-help">{feedback}</p>}
  </div></article>
  {status==="planned"&&<article className="panel"><div className="panel-head"><div><h2>Gerenciar acompanhamento</h2></div></div><div className="panel-body form-grid-two"><label className="field"><span>Nova data</span><input className="input" type="date" value={newDue} onChange={e=>setNewDue(e.target.value)}/></label><div style={{alignSelf:"end"}}><button type="button" className="button ghost" disabled={loading} onClick={reschedule}><RefreshCcw size={16}/>Reagendar</button></div><label className="field field-span-two"><span>Resultado do contato</span><input className="input" value={outcome} onChange={e=>setOutcome(e.target.value)}/></label><label className="field field-span-two"><span>Observações</span><textarea className="textarea" rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="field-span-two"><button type="button" className="button gold" disabled={loading} onClick={complete}><Check size={16}/>Concluir pós-venda</button></div></div></article>}
 </div>
}
