/* eslint-disable @next/next/no-img-element */
"use client";
import { useRef,useState } from "react";
import { ImagePlus,LoaderCircle,RefreshCw } from "lucide-react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
type ImageField="image_url"|"secondary_image_url";const MAX=10*1024*1024;const ALLOWED=new Set(["image/jpeg","image/png","image/webp"]);
async function optimize(file:File){const url=URL.createObjectURL(file);try{const img=await new Promise<HTMLImageElement>((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(new Error("Não foi possível ler a imagem."));i.src=url;});const scale=Math.min(1,1200/Math.max(img.naturalWidth,img.naturalHeight));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Não foi possível otimizar a imagem.");ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error("Não foi possível converter a imagem.")),"image/webp",.82));return new File([blob],"produto.webp",{type:"image/webp"});}finally{URL.revokeObjectURL(url)}}
function Slot({productId,field,label,imageUrl,onUploaded}:{productId:string;field:ImageField;label:string;imageUrl:string|null;onUploaded:(f:ImageField,u:string)=>void}){const ref=useRef<HTMLInputElement>(null);const[loading,setLoading]=useState(false);const[message,setMessage]=useState<string|null>(null);async function handle(file?:File){if(!file)return;setMessage(null);if(!ALLOWED.has(file.type)){setMessage("Use JPG, PNG ou WEBP.");return}if(file.size>MAX){setMessage("A imagem original precisa ter no máximo 10 MB.");return}setLoading(true);try{const optimized=await optimize(file);const supabase=createClient();const path=`${productId}/${crypto.randomUUID()}.webp`;const{error}=await supabase.storage.from("product-images").upload(path,optimized,{contentType:"image/webp"});if(error)throw error;const{data}=supabase.storage.from("product-images").getPublicUrl(path);const{error:updateError}=await supabase.from("products").update({[field]:data.publicUrl}).eq("id",productId);if(updateError)throw updateError;onUploaded(field,data.publicUrl);setMessage(`Foto otimizada (${Math.max(1,Math.round(optimized.size/1024))} KB).`);}catch(error){setMessage(error instanceof Error?error.message:"Não foi possível enviar a foto.");}finally{setLoading(false);if(ref.current)ref.current.value=""}}
return <div className="product-image-slot"><div className="product-image-frame">{imageUrl?<img src={imageUrl} alt={label} loading="lazy"/>:<div className="product-image-placeholder"><ImagePlus size={34}/><span>Sem foto</span></div>}</div><div className="product-image-slot-footer"><div><strong>{label}</strong><span>Reduzida e convertida para WebP automaticamente</span></div><button className="button ghost" type="button" disabled={loading} onClick={()=>ref.current?.click()}>{loading?<LoaderCircle className="spin" size={16}/>:imageUrl?<RefreshCw size={16}/>:<ImagePlus size={16}/>} {loading?"Otimizando":imageUrl?"Trocar foto":"Adicionar foto"}</button><input ref={ref} className="visually-hidden" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void handle(e.target.files?.[0])}/></div>{message&&<p className="upload-message">{message}</p>}</div>}
export function ProductImageUploader({productId,initialImageUrl,initialSecondaryImageUrl}:{productId:string;initialImageUrl:string|null;initialSecondaryImageUrl:string|null}){const router=useRouter();const[images,setImages]=useState({image_url:initialImageUrl,secondary_image_url:initialSecondaryImageUrl});const uploaded=(field:ImageField,url:string)=>{setImages(c=>({...c,[field]:url}));router.refresh();};return <div className="product-image-grid"><Slot productId={productId} field="image_url" label="Foto principal" imageUrl={images.image_url} onUploaded={uploaded}/><Slot productId={productId} field="secondary_image_url" label="Segunda foto" imageUrl={images.secondary_image_url} onUploaded={uploaded}/></div>}
