/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { ArrowLeft,CalendarDays,ImageIcon,MessageSquareText,Phone,UserRound } from "lucide-react";
import { notFound } from "next/navigation";
import { Badge } from "@/components/badge";
import { DemoBanner } from "@/components/demo-banner";
import { PageHeader } from "@/components/page-header";
import { getLeadDetails } from "@/lib/data";
import { formatDate } from "@/lib/format";
function Line({label,value}:{label:string;value:React.ReactNode}){if(value==null||value===""||value==="—")return null;return <div className="sale-detail-line"><span>{label}</span><strong>{value}</strong></div>}
export default async function LeadDetailsPage({params}:{params:Promise<{id:string}>}){const{id}=await params;const lead=await getLeadDetails(id);if(!lead)notFound();return <><DemoBanner/><PageHeader eyebrow="Lead" title={lead.customer_name} description="Informações do contato comercial sem campos de pagamento ou entrega." action={<Link className="button ghost" href="/leads"><ArrowLeft size={16}/>Voltar</Link>}/><section className="lead-details-layout"><div className="lead-details-main"><article className="panel"><div className="panel-head"><div><h2>Produto de interesse</h2><p>Item relacionado ao contato</p></div></div><div className="panel-body"><div className="lead-product-card"><div className="sale-item-image">{lead.product_image_url?<img src={lead.product_image_url} alt={lead.product_name??"Produto"}/>:<ImageIcon size={30}/>}</div><div>{lead.product_id?<Link className="cell-main table-link" href={`/produtos/${lead.product_id}`}>{lead.product_name??"Produto"}</Link>:<strong>{lead.product_name??"Produto não informado"}</strong>}<span>{[lead.category,lead.brand].filter(Boolean).join(" · ")}</span></div></div></div></article>{lead.notes&&<article className="panel"><div className="panel-head"><div><h2>Observações</h2><p>Contexto do atendimento</p></div><MessageSquareText size={19}/></div><div className="panel-body"><p className="sale-notes">{lead.notes}</p></div></article>}</div><aside className="sale-details-side"><article className="panel"><div className="panel-head"><div><h2>Situação</h2><p>Etapa atual</p></div><CalendarDays size={19}/></div><div className="panel-body sale-detail-list"><Line label="Data do orçamento" value={formatDate(lead.lead_at)}/><Line label="Status" value={<Badge value={lead.lead_status??lead.general_status}/>}/></div></article><article className="panel"><div className="panel-head"><div><h2>Cliente</h2><p>Dados disponíveis</p></div><UserRound size={19}/></div><div className="panel-body sale-detail-list"><Line label="Nome" value={lead.customer_id?<Link className="table-link" href={`/clientes/${lead.customer_id}`}>{lead.customer_name}</Link>:lead.customer_name}/><Line label="Telefone" value={lead.phone?<span className="detail-with-icon"><Phone size={14}/>{lead.phone}</span>:null}/><Line label="Cidade" value={lead.city}/><Line label="Referência" value={lead.reference}/></div></article></aside></section></>}
