create or replace function public.central_global_search(p_query text,p_limit integer default 60)
returns table(result_type text,entity_id uuid,title text,subtitle text,href text,operation_scope text,score integer)
language plpgsql stable security definer set search_path=public as $$
declare v_query text:=lower(btrim(coalesce(p_query,'')));
begin
  if not (public.current_user_role()='admin' or public.can_access_operation('supplements') or public.can_access_operation('fitness') or public.can_access_marketing()) then raise exception 'Acesso negado'; end if;
  if length(v_query)<2 then return; end if;
  return query with results(result_type,entity_id,title,subtitle,href,operation_scope,score) as (
    select 'contact'::text,c.id,c.display_name,concat_ws(' · ',nullif(c.phone,''),nullif(c.email,''),case when c.instagram_username is not null then '@'||c.instagram_username end),'/central/clientes/'||c.id::text,c.operation_scope,case when lower(c.display_name)=v_query then 100 when lower(coalesce(c.phone,''))=v_query or lower(coalesce(c.email,''))=v_query then 95 when lower(c.display_name) like v_query||'%' then 85 else 70 end from public.central_contacts c where public.central_can_access_scope(c.operation_scope) and (lower(c.display_name) like '%'||v_query||'%' or lower(coalesce(c.phone,'')) like '%'||v_query||'%' or lower(coalesce(c.email,'')) like '%'||v_query||'%' or lower(coalesce(c.instagram_username,'')) like '%'||v_query||'%')
    union all select 'conversation',v.conversation_id,v.contact_name,concat_ws(' · ',initcap(v.provider),nullif(v.last_message_body,'')),'/central/inbox?conversa='||v.conversation_id::text,v.operation_scope,case when lower(v.contact_name)=v_query then 92 when lower(v.contact_name) like v_query||'%' then 82 else 66 end from public.central_inbox_overview v where public.central_can_access_scope(v.operation_scope) and (lower(v.contact_name) like '%'||v_query||'%' or lower(coalesce(v.last_message_body,'')) like '%'||v_query||'%' or lower(coalesce(v.phone,'')) like '%'||v_query||'%')
    union all select 'product',p.id,p.name,concat_ws(' · ',nullif(p.brand,''),nullif(p.category,'')),'/produtos/'||p.id::text,'supplements',case when lower(p.name)=v_query then 96 when lower(p.name) like v_query||'%' then 84 else 62 end from public.products p where public.can_access_operation('supplements') and coalesce(p.active,true) and (lower(p.name) like '%'||v_query||'%' or lower(coalesce(p.brand,'')) like '%'||v_query||'%' or lower(coalesce(p.category,'')) like '%'||v_query||'%' or lower(coalesce(p.keywords,'')) like '%'||v_query||'%')
    union all select 'fitness_product',p.id,p.name,concat_ws(' · ',nullif(p.category,''),nullif(p.description,'')),'/fitness/produtos','fitness',case when lower(p.name)=v_query then 94 when lower(p.name) like v_query||'%' then 82 else 60 end from public.fitness_products p where public.can_access_operation('fitness') and coalesce(p.active,true) and (lower(p.name) like '%'||v_query||'%' or lower(coalesce(p.category,'')) like '%'||v_query||'%' or lower(coalesce(p.description,'')) like '%'||v_query||'%')
    union all select 'partner',p.id,p.name,concat_ws(' · ',nullif(p.contact_name,''),nullif(p.city,''),nullif(p.partner_type,'')),'/parceiros/'||p.id::text,'supplements',case when lower(p.name)=v_query then 91 when lower(p.name) like v_query||'%' then 80 else 58 end from public.partners p where (public.can_access_operation('supplements') or public.can_manage_users()) and coalesce(p.active,true) and (lower(p.name) like '%'||v_query||'%' or lower(coalesce(p.contact_name,'')) like '%'||v_query||'%' or lower(coalesce(p.city,'')) like '%'||v_query||'%' or lower(coalesce(p.phone,'')) like '%'||v_query||'%')
    union all select 'task',t.id,t.title,concat_ws(' · ',initcap(t.operation_scope),initcap(replace(t.category,'_',' ')),to_char(t.due_at,'DD/MM/YYYY HH24:MI')),'/central/agenda',t.operation_scope,case when lower(t.title)=v_query then 88 when lower(t.title) like v_query||'%' then 76 else 54 end from public.operational_tasks t where public.central_can_access_scope(t.operation_scope) and t.status in ('planned','pending') and (lower(t.title) like '%'||v_query||'%' or lower(coalesce(t.notes,'')) like '%'||v_query||'%')
    union all select 'media',m.id,coalesce(nullif(m.original_filename,''),'Arquivo de mídia'),concat_ws(' · ',initcap(m.operation_scope),nullif(m.description_ai,'')),'/central/midia/'||m.id::text,m.operation_scope,case when lower(coalesce(m.original_filename,''))=v_query then 86 when lower(coalesce(m.original_filename,'')) like v_query||'%' then 74 else 52 end from public.central_media_assets m where public.central_can_access_scope(m.operation_scope) and (lower(coalesce(m.original_filename,'')) like '%'||v_query||'%' or lower(coalesce(m.description_ai,'')) like '%'||v_query||'%' or lower(coalesce(m.search_text,'')) like '%'||v_query||'%')
  ) select r.result_type,r.entity_id,r.title,r.subtitle,r.href,r.operation_scope,r.score from results r order by r.score desc,r.title limit least(greatest(coalesce(p_limit,60),1),150);
end;$$;
revoke all on function public.central_global_search(text,integer) from public,anon;
grant execute on function public.central_global_search(text,integer) to authenticated;
