-- Candinho Suplementos — fluxo de orçamento, desconto, brinde e conversão em venda.
-- Mantém a função create_sale existente intacta e adiciona um novo fluxo isolado.

alter table public.sales
  add column if not exists discount_amount numeric(12,2) not null default 0,
  add column if not exists gift_product_id uuid references public.products(id) on delete restrict,
  add column if not exists gift_quantity integer not null default 0,
  add column if not exists gift_unit_cost numeric(12,2) not null default 0;

alter table public.sales drop constraint if exists sales_discount_amount_nonnegative;
alter table public.sales add constraint sales_discount_amount_nonnegative check (discount_amount >= 0);
alter table public.sales drop constraint if exists sales_gift_quantity_nonnegative;
alter table public.sales add constraint sales_gift_quantity_nonnegative check (gift_quantity >= 0);
alter table public.sales drop constraint if exists sales_gift_unit_cost_nonnegative;
alter table public.sales add constraint sales_gift_unit_cost_nonnegative check (gift_unit_cost >= 0);

create table if not exists public.sales_quotes (
  id uuid primary key default gen_random_uuid(),
  quote_number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id) on delete restrict,
  location_id uuid not null references public.locations(id) on delete restrict,
  lead_id uuid references public.sales(id) on delete set null,
  sale_id uuid references public.sales(id) on delete set null,
  status text not null default 'quoted' check (status in ('quoted','confirmed','lost','cancelled')),
  quoted_on date not null default ((now() at time zone 'America/Sao_Paulo')::date),
  valid_until date not null,
  gross_amount numeric(12,2) not null default 0 check (gross_amount >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  total_amount numeric(12,2) not null default 0 check (total_amount >= 0),
  gift_product_id uuid references public.products(id) on delete restrict,
  gift_quantity integer not null default 0 check (gift_quantity >= 0),
  payment_mode text not null default 'receivable' check (payment_mode in ('receivable','paid','combined')),
  payment_method text,
  paid_on date,
  payment_due_on date,
  delivered boolean not null default false,
  delivered_on date,
  delivery_due_on date,
  schedule_post_sale boolean not null default true,
  post_sale_due_on date,
  partner_id uuid references public.partners(id) on delete set null,
  notes text,
  confirmed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.sales_quotes(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  unit_cost numeric(12,2) not null check (unit_cost >= 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  total_cost numeric(12,2) generated always as (quantity::numeric * unit_cost) stored,
  total_price numeric(12,2) generated always as (quantity::numeric * unit_price) stored,
  created_at timestamptz not null default now(),
  unique(quote_id, product_id)
);

create index if not exists sales_quotes_customer_idx on public.sales_quotes(customer_id, quoted_on desc);
create index if not exists sales_quotes_lead_idx on public.sales_quotes(lead_id) where lead_id is not null;
create index if not exists sales_quotes_sale_idx on public.sales_quotes(sale_id) where sale_id is not null;
create index if not exists sales_quotes_status_idx on public.sales_quotes(status, quoted_on desc);
create index if not exists sales_quote_items_quote_idx on public.sales_quote_items(quote_id);

alter table public.sales_quotes enable row level security;
alter table public.sales_quote_items enable row level security;

drop policy if exists sales_quotes_read on public.sales_quotes;
create policy sales_quotes_read on public.sales_quotes for select to authenticated using (true);
drop policy if exists sales_quotes_write on public.sales_quotes;
create policy sales_quotes_write on public.sales_quotes for all to authenticated using (public.can_write()) with check (public.can_write());

drop policy if exists sales_quote_items_read on public.sales_quote_items;
create policy sales_quote_items_read on public.sales_quote_items for select to authenticated using (true);
drop policy if exists sales_quote_items_write on public.sales_quote_items;
create policy sales_quote_items_write on public.sales_quote_items for all to authenticated using (public.can_write()) with check (public.can_write());

grant select, insert, update, delete on public.sales_quotes, public.sales_quote_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Totais da venda passam a considerar desconto geral e custo do brinde.
create or replace function public.refresh_sale_totals()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale_id uuid;
  v_item_cost numeric(12,2);
  v_item_amount numeric(12,2);
  v_discount numeric(12,2);
  v_gift_cost numeric(12,2);
begin
  v_sale_id := coalesce(new.sale_id, old.sale_id);

  select
    coalesce(sum(si.total_cost),0)::numeric(12,2),
    coalesce(sum(si.total_price),0)::numeric(12,2)
  into v_item_cost, v_item_amount
  from public.sale_items si
  where si.sale_id = v_sale_id;

  select
    coalesce(s.discount_amount,0)::numeric(12,2),
    (coalesce(s.gift_quantity,0) * coalesce(s.gift_unit_cost,0))::numeric(12,2)
  into v_discount, v_gift_cost
  from public.sales s
  where s.id = v_sale_id;

  update public.sales
  set
    total_cost = (v_item_cost + coalesce(v_gift_cost,0))::numeric(12,2),
    total_amount = greatest(v_item_amount - coalesce(v_discount,0),0)::numeric(12,2),
    total_profit = (greatest(v_item_amount - coalesce(v_discount,0),0) - (v_item_cost + coalesce(v_gift_cost,0)))::numeric(12,2),
    updated_at = now()
  where id = v_sale_id;

  return coalesce(new, old);
end;
$$;

create or replace function public.create_budget(
  p_mode text,
  p_customer_id uuid,
  p_location_id uuid,
  p_quoted_on date,
  p_valid_until date,
  p_items jsonb,
  p_discount_amount numeric default 0,
  p_gift_product_id uuid default null,
  p_gift_quantity integer default 0,
  p_payment_mode text default 'receivable',
  p_paid_on date default null,
  p_payment_method text default null,
  p_payment_due_on date default null,
  p_delivered boolean default false,
  p_delivered_on date default null,
  p_delivery_due_on date default null,
  p_schedule_post_sale boolean default true,
  p_post_sale_due_on date default null,
  p_notes text default null,
  p_partner_id uuid default null,
  p_existing_quote_id uuid default null
)
returns table(quote_id uuid, sale_id uuid, lead_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_quote_id uuid;
  v_sale_id uuid;
  v_lead_id uuid;
  v_customer public.customers%rowtype;
  v_location public.locations%rowtype;
  v_partner public.partners%rowtype;
  v_product public.products%rowtype;
  v_gift public.products%rowtype;
  v_item record;
  v_quote public.sales_quotes%rowtype;
  v_quoted_on date := coalesce(p_quoted_on,(now() at time zone 'America/Sao_Paulo')::date);
  v_valid_until date;
  v_quoted_at timestamptz;
  v_paid_at timestamptz;
  v_delivered_at timestamptz;
  v_payment_status public.payment_status := 'receivable';
  v_delivery_status public.delivery_status := 'to_deliver';
  v_general_status public.sale_general_status := 'active';
  v_payment_condition text := 'A receber';
  v_item_condition text;
  v_sale_condition text;
  v_physical integer;
  v_reserved integer;
  v_available integer;
  v_reserve integer;
  v_reservation_status text;
  v_gross numeric(12,2) := 0;
  v_discount numeric(12,2) := greatest(coalesce(p_discount_amount,0),0);
  v_total numeric(12,2) := 0;
  v_gift_cost numeric(12,2) := 0;
  v_allowed_methods constant text[] := array['Pix','Dinheiro','Cartão','Link de Pagamento','Pagamento fracionado'];
begin
  if not public.can_write() then raise exception 'Usuário sem permissão para registrar orçamentos'; end if;
  if p_mode not in ('confirmed','quote') then raise exception 'Tipo de salvamento inválido'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'Adicione pelo menos um produto ao orçamento'; end if;
  if jsonb_array_length(p_items)>20 then raise exception 'O orçamento pode ter no máximo 20 itens'; end if;
  if p_gift_quantity is null or p_gift_quantity < 0 then raise exception 'Quantidade de brinde inválida'; end if;
  if p_gift_product_id is null and coalesce(p_gift_quantity,0) > 0 then raise exception 'Selecione o produto do brinde'; end if;
  if p_gift_product_id is not null and coalesce(p_gift_quantity,0) = 0 then p_gift_quantity := 1; end if;
  if p_payment_mode not in ('receivable','paid','combined') then raise exception 'Situação do pagamento inválida'; end if;
  if p_payment_method is not null and not (p_payment_method = any(v_allowed_methods)) then raise exception 'Forma de pagamento inválida'; end if;
  if p_mode='confirmed' and p_payment_mode='paid' and p_paid_on is null then raise exception 'Informe a data do pagamento'; end if;
  if p_payment_mode='combined' and p_payment_due_on is null then raise exception 'Informe a data combinada para pagamento'; end if;
  if p_mode='confirmed' and p_delivered and p_delivered_on is null then raise exception 'Informe a data da entrega'; end if;

  select * into v_customer from public.customers where id=p_customer_id and active;
  if not found then raise exception 'Cliente não encontrado ou inativo'; end if;
  select * into v_location from public.locations where id=p_location_id and active and tracks_inventory;
  if not found then raise exception 'Estoque de origem inválido'; end if;
  if p_partner_id is not null then
    select * into v_partner from public.partners where id=p_partner_id and lower(partner_type)<>'supplier' and coalesce(active,true);
    if not found then raise exception 'Parceiro inválido ou inativo'; end if;
  end if;
  if p_gift_product_id is not null then
    select * into v_gift from public.products where id=p_gift_product_id and active;
    if not found then raise exception 'Produto de brinde não encontrado ou inativo'; end if;
    v_gift_cost := v_gift.cost_price;
  end if;

  if exists(
    select 1 from jsonb_to_recordset(p_items) as x(product_id uuid,quantity integer,unit_price numeric)
    group by product_id having count(*)>1
  ) then raise exception 'O mesmo produto foi adicionado mais de uma vez'; end if;

  v_valid_until := coalesce(p_valid_until, v_quoted_on + 7);
  if v_valid_until < v_quoted_on then raise exception 'A validade do orçamento não pode ser anterior à data do orçamento'; end if;
  v_quoted_at := (v_quoted_on::timestamp + interval '12 hours') at time zone 'America/Sao_Paulo';

  if p_payment_mode='paid' then
    v_payment_condition := 'Pago';
    if p_paid_on is not null then v_paid_at := (p_paid_on::timestamp+interval '12 hours') at time zone 'America/Sao_Paulo'; end if;
    if p_mode='confirmed' then v_payment_status := 'received'; end if;
  elsif p_payment_mode='combined' then
    v_payment_condition := 'Pagamento combinado';
  end if;
  if p_mode='confirmed' and p_delivered then
    v_delivery_status := 'delivered';
    v_delivered_at := (p_delivered_on::timestamp+interval '12 hours') at time zone 'America/Sao_Paulo';
  end if;
  if p_mode='confirmed' and v_payment_status='received' and v_delivery_status='delivered' then v_general_status := 'finalized'; end if;

  if p_existing_quote_id is not null then
    select * into v_quote from public.sales_quotes where id=p_existing_quote_id for update;
    if not found then raise exception 'Orçamento anterior não encontrado'; end if;
    if v_quote.status <> 'quoted' then raise exception 'Este orçamento não está disponível para conversão'; end if;
    v_quote_id := v_quote.id;
    v_lead_id := v_quote.lead_id;
    update public.sales_quotes set
      customer_id=p_customer_id,location_id=p_location_id,quoted_on=v_quoted_on,valid_until=v_valid_until,
      discount_amount=v_discount,gift_product_id=p_gift_product_id,gift_quantity=coalesce(p_gift_quantity,0),
      payment_mode=p_payment_mode,payment_method=p_payment_method,paid_on=p_paid_on,payment_due_on=p_payment_due_on,
      delivered=coalesce(p_delivered,false),delivered_on=p_delivered_on,delivery_due_on=p_delivery_due_on,
      schedule_post_sale=coalesce(p_schedule_post_sale,true),post_sale_due_on=p_post_sale_due_on,partner_id=p_partner_id,
      notes=nullif(btrim(p_notes),''),updated_at=now()
    where id=v_quote_id;
    delete from public.sales_quote_items qi where qi.quote_id=v_quote_id;
  else
    insert into public.sales_quotes(
      customer_id,location_id,status,quoted_on,valid_until,discount_amount,gift_product_id,gift_quantity,
      payment_mode,payment_method,paid_on,payment_due_on,delivered,delivered_on,delivery_due_on,
      schedule_post_sale,post_sale_due_on,partner_id,notes
    ) values(
      p_customer_id,p_location_id,'quoted',v_quoted_on,v_valid_until,v_discount,p_gift_product_id,coalesce(p_gift_quantity,0),
      p_payment_mode,p_payment_method,p_paid_on,p_payment_due_on,coalesce(p_delivered,false),p_delivered_on,p_delivery_due_on,
      coalesce(p_schedule_post_sale,true),p_post_sale_due_on,p_partner_id,nullif(btrim(p_notes),'')
    ) returning id into v_quote_id;
  end if;

  for v_item in
    select product_id,quantity,unit_price
    from jsonb_to_recordset(p_items) as x(product_id uuid,quantity integer,unit_price numeric)
  loop
    if v_item.quantity is null or v_item.quantity<=0 then raise exception 'A quantidade de cada produto deve ser maior que zero'; end if;
    if v_item.unit_price is null or v_item.unit_price<0 then raise exception 'Preço de venda inválido'; end if;
    select * into v_product from public.products where id=v_item.product_id and active;
    if not found then raise exception 'Produto não encontrado ou inativo'; end if;
    insert into public.sales_quote_items(quote_id,product_id,quantity,unit_cost,unit_price)
    values(v_quote_id,v_product.id,v_item.quantity,v_product.cost_price,v_item.unit_price);
    v_gross := v_gross + (v_item.quantity * v_item.unit_price);
  end loop;

  if v_discount > v_gross then raise exception 'O desconto não pode ser maior que o subtotal do orçamento'; end if;
  v_total := greatest(v_gross-v_discount,0);
  update public.sales_quotes set gross_amount=v_gross,total_amount=v_total,updated_at=now() where id=v_quote_id;

  if p_mode='quote' then
    if v_lead_id is null then
      insert into public.sales(
        record_type,customer_id,location_id,reference,city,phone,general_status,payment_status,delivery_status,
        lead_status,payment_method,payment_condition,payment_due_at,quoted_at,notes,stock_deducted,
        total_cost,total_amount,total_profit,idempotency_key,discount_amount,gift_product_id,gift_quantity,gift_unit_cost
      ) values(
        'lead',v_customer.id,v_location.id,v_customer.reference,v_customer.city,v_customer.phone,'pending','not_applicable','not_applicable',
        'Cotação',p_payment_method,v_payment_condition,p_payment_due_on,v_quoted_at,nullif(btrim(p_notes),''),false,
        0,0,0,'app:create-budget-lead:'||v_quote_id::text,v_discount,p_gift_product_id,coalesce(p_gift_quantity,0),v_gift_cost
      ) returning id into v_lead_id;
    else
      update public.sales set
        customer_id=v_customer.id,location_id=v_location.id,reference=v_customer.reference,city=v_customer.city,phone=v_customer.phone,
        lead_status='Cotação',general_status='pending',payment_method=p_payment_method,payment_condition=v_payment_condition,
        payment_due_at=p_payment_due_on,quoted_at=v_quoted_at,notes=nullif(btrim(p_notes),''),discount_amount=v_discount,
        gift_product_id=p_gift_product_id,gift_quantity=coalesce(p_gift_quantity,0),gift_unit_cost=v_gift_cost,updated_at=now()
      where id=v_lead_id and record_type='lead';
      delete from public.sale_items where sale_id=v_lead_id;
    end if;

    insert into public.sale_items(sale_id,product_id,quantity,unit_cost,unit_price,price_condition)
    select
      v_lead_id, qi.product_id, qi.quantity, qi.unit_cost, qi.unit_price,
      case when qi.unit_price=p.cost_price then 'Custo' when qi.unit_price=p.sale_price then 'Preço normal' when qi.unit_price<p.sale_price then 'Desconto' else 'Preço combinado' end
    from public.sales_quote_items qi join public.products p on p.id=qi.product_id
    where qi.quote_id=v_quote_id;

    update public.sales_quotes set lead_id=v_lead_id,status='quoted',updated_at=now() where id=v_quote_id;
    insert into public.audit_events(entity_type,entity_id,action,details)
    values('quote',v_quote_id,'created',jsonb_build_object('mode','quote','lead_id',v_lead_id,'customer_id',p_customer_id,'total_amount',v_total));
    return query select v_quote_id, null::uuid, v_lead_id;
    return;
  end if;

  -- Orçamento confirmado: cria a venda normal preservando o fluxo atual de reservas/entrega.
  insert into public.sales(
    record_type,customer_id,location_id,reference,city,phone,general_status,payment_status,delivery_status,
    payment_method,payment_condition,payment_due_at,partnership,partner_id,quoted_at,paid_at,delivered_at,delivery_due_at,
    post_sale_due_at,notes,stock_deducted,total_cost,total_amount,total_profit,idempotency_key,
    discount_amount,gift_product_id,gift_quantity,gift_unit_cost
  ) values(
    'sale',v_customer.id,v_location.id,v_customer.reference,v_customer.city,v_customer.phone,v_general_status,v_payment_status,v_delivery_status,
    case when p_payment_mode='paid' then p_payment_method else null end,v_payment_condition,case when p_payment_mode='combined' then p_payment_due_on else null end,
    case when p_partner_id is not null then v_partner.name else null end,p_partner_id,v_quoted_at,v_paid_at,v_delivered_at,p_delivery_due_on,
    case when coalesce(p_schedule_post_sale,true) then p_post_sale_due_on else null end,nullif(btrim(p_notes),''),coalesce(p_delivered,false),
    0,0,0,'app:create-budget-sale:'||v_quote_id::text,v_discount,p_gift_product_id,coalesce(p_gift_quantity,0),v_gift_cost
  ) returning id into v_sale_id;

  for v_item in
    select qi.*,p.sale_price as standard_price
    from public.sales_quote_items qi join public.products p on p.id=qi.product_id
    where qi.quote_id=v_quote_id
  loop
    v_item_condition := case when v_item.unit_price=v_item.unit_cost then 'Custo' when v_item.unit_price=v_item.standard_price then 'Preço normal' when v_item.unit_price<v_item.standard_price then 'Desconto' else 'Preço combinado' end;
    insert into public.sale_items(sale_id,product_id,quantity,unit_cost,unit_price,price_condition)
    values(v_sale_id,v_item.product_id,v_item.quantity,v_item.unit_cost,v_item.unit_price,v_item_condition);

    insert into public.stock_balances(product_id,location_id,quantity)
    values(v_item.product_id,v_location.id,0) on conflict(product_id,location_id) do nothing;
    select quantity into v_physical from public.stock_balances where product_id=v_item.product_id and location_id=v_location.id for update;
    select coalesce(sum(quantity_reserved),0)::integer into v_reserved
    from public.stock_reservations where product_id=v_item.product_id and location_id=v_location.id and status in ('reserved','partial');
    v_available := greatest(v_physical-v_reserved,0);

    if p_delivered then
      if v_available<v_item.quantity then raise exception 'Estoque disponível insuficiente para entregar o produto. Disponível em %: %',v_location.code,v_available; end if;
      insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,sale_id,notes,idempotency_key)
      values(v_item.product_id,v_location.id,'sale',-v_item.quantity,v_sale_id,'Baixa automática na criação de orçamento confirmado entregue','app:create-budget-delivery:'||v_sale_id::text||':'||v_item.id::text);
    else
      v_reserve := least(v_item.quantity,v_available);
      v_reservation_status := case when v_reserve=v_item.quantity then 'reserved' when v_reserve>0 then 'partial' else 'awaiting_stock' end;
      insert into public.stock_reservations(sale_id,sale_item_id,product_id,location_id,quantity_requested,quantity_reserved,status,reserved_at,notes)
      select v_sale_id,si.id,v_item.product_id,v_location.id,v_item.quantity,v_reserve,v_reservation_status,
             case when v_reserve>0 then now() else null end,
             case when v_reserve<v_item.quantity then 'Aguardando reposição de estoque' else 'Reservado para a venda' end
      from public.sale_items si where si.sale_id=v_sale_id and si.product_id=v_item.product_id limit 1;
    end if;
  end loop;

  -- O brinde é baixado imediatamente quando o orçamento vira venda, mesmo se os demais itens ainda estiverem reservados.
  if p_gift_product_id is not null and coalesce(p_gift_quantity,0)>0 then
    insert into public.stock_balances(product_id,location_id,quantity)
    values(p_gift_product_id,v_location.id,0) on conflict(product_id,location_id) do nothing;
    select quantity into v_physical from public.stock_balances where product_id=p_gift_product_id and location_id=v_location.id for update;
    select coalesce(sum(quantity_reserved),0)::integer into v_reserved
    from public.stock_reservations where product_id=p_gift_product_id and location_id=v_location.id and status in ('reserved','partial');
    v_available := greatest(v_physical-v_reserved,0);
    if v_available<p_gift_quantity then raise exception 'Estoque insuficiente para o brinde %. Disponível em %: %',v_gift.name,v_location.code,v_available; end if;
    insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,sale_id,notes,idempotency_key)
    values(p_gift_product_id,v_location.id,'sale',-p_gift_quantity,v_sale_id,'Baixa automática do brinde do orçamento confirmado','app:create-budget-gift:'||v_sale_id::text||':'||p_gift_product_id::text);
  end if;

  select case when count(distinct price_condition)=1 then min(price_condition) else 'Preço combinado' end
  into v_sale_condition from public.sale_items si where si.sale_id=v_sale_id;
  update public.sales set price_condition=v_sale_condition where id=v_sale_id;

  -- Recalcula explicitamente depois que desconto e brinde já estão associados à venda.
  update public.sales s set
    total_cost = (coalesce(x.item_cost,0) + (coalesce(s.gift_quantity,0)*coalesce(s.gift_unit_cost,0)))::numeric(12,2),
    total_amount = greatest(coalesce(x.item_amount,0)-coalesce(s.discount_amount,0),0)::numeric(12,2),
    total_profit = (greatest(coalesce(x.item_amount,0)-coalesce(s.discount_amount,0),0) - (coalesce(x.item_cost,0)+(coalesce(s.gift_quantity,0)*coalesce(s.gift_unit_cost,0))))::numeric(12,2)
  from (
    select si.sale_id,sum(si.total_cost)::numeric(12,2) item_cost,sum(si.total_price)::numeric(12,2) item_amount
    from public.sale_items si where si.sale_id=v_sale_id group by si.sale_id
  ) x where s.id=v_sale_id and x.sale_id=s.id;

  select total_amount into v_total from public.sales where id=v_sale_id;
  if p_payment_mode='paid' then
    insert into public.sale_payment_entries(sale_id,amount,payment_method,received_at,notes)
    values(v_sale_id,v_total,p_payment_method,v_paid_at,'Pagamento registrado na confirmação do orçamento');
  end if;

  update public.sales_quotes set status='confirmed',sale_id=v_sale_id,confirmed_at=now(),updated_at=now() where id=v_quote_id;
  if v_lead_id is not null then
    update public.sales set lead_status='Convertido',general_status='finalized',updated_at=now() where id=v_lead_id and record_type='lead';
  end if;

  insert into public.audit_events(entity_type,entity_id,action,details)
  values('quote',v_quote_id,'confirmed',jsonb_build_object('sale_id',v_sale_id,'lead_id',v_lead_id,'customer_id',p_customer_id,'discount_amount',v_discount,'gift_product_id',p_gift_product_id,'total_amount',v_total));
  insert into public.audit_events(entity_type,entity_id,action,details)
  values('sale',v_sale_id,'created',jsonb_build_object('source','quote','quote_id',v_quote_id,'customer_id',v_customer.id,'location_id',v_location.id,'quoted_on',v_quoted_on,'payment_mode',p_payment_mode,'delivered',p_delivered,'partner_id',p_partner_id,'price_condition',v_sale_condition,'discount_amount',v_discount,'gift_product_id',p_gift_product_id));

  return query select v_quote_id, v_sale_id, v_lead_id;
end;
$$;

revoke all on function public.create_budget(text,uuid,uuid,date,date,jsonb,numeric,uuid,integer,text,date,text,date,boolean,date,date,boolean,date,text,uuid,uuid) from public, anon;
grant execute on function public.create_budget(text,uuid,uuid,date,date,jsonb,numeric,uuid,integer,text,date,text,date,boolean,date,date,boolean,date,text,uuid,uuid) to authenticated, service_role;

-- Cancelamento passa a devolver também o estoque do brinde, que é baixado no momento da confirmação.
create or replace function public.cancel_sale(p_sale_id uuid, p_reason text default null)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale public.sales%rowtype;
  v_item public.sale_items%rowtype;
  v_released integer := 0;
  v_restored integer := 0;
begin
  if not public.can_write() then raise exception 'Usuário sem permissão para cancelar vendas'; end if;
  select * into v_sale from public.sales where id=p_sale_id and record_type='sale' for update;
  if not found then raise exception 'Venda não encontrada'; end if;
  if v_sale.general_status='cancelled' then return v_sale.id; end if;

  if v_sale.stock_deducted then
    for v_item in select * from public.sale_items where sale_id=p_sale_id loop
      insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,sale_id,notes,idempotency_key)
      values(v_item.product_id,v_sale.location_id,'cancellation',v_item.quantity,v_sale.id,'Estorno do cancelamento da venda '||v_sale.id,'cancel:'||v_sale.id||':item:'||v_item.id)
      on conflict(idempotency_key) do nothing;
      v_restored:=v_restored+v_item.quantity;
    end loop;
  else
    update public.stock_reservations
    set status='released',quantity_reserved=0,released_at=now(),updated_at=now(),notes=case when nullif(btrim(notes),'') is null then 'Reserva liberada por cancelamento da venda' else notes||' | Reserva liberada por cancelamento da venda' end
    where sale_id=p_sale_id and status in ('reserved','partial','awaiting_stock');
    get diagnostics v_released = row_count;
  end if;

  if v_sale.gift_product_id is not null and coalesce(v_sale.gift_quantity,0)>0 then
    insert into public.inventory_movements(product_id,location_id,movement_type,quantity_delta,sale_id,notes,idempotency_key)
    values(v_sale.gift_product_id,v_sale.location_id,'cancellation',v_sale.gift_quantity,v_sale.id,'Estorno do brinde no cancelamento da venda '||v_sale.id,'cancel:'||v_sale.id||':gift:'||v_sale.gift_product_id)
    on conflict(idempotency_key) do nothing;
    v_restored:=v_restored+v_sale.gift_quantity;
  end if;

  update public.sales set general_status='cancelled',cancelled_at=now(),cancellation_reason=nullif(btrim(p_reason),''),stock_deducted=false,updated_at=now() where id=p_sale_id;
  update public.deliveries set status=case when status='Entregue' then status else 'Cancelado' end where sale_id=p_sale_id;
  update public.sales_quotes set status='cancelled',updated_at=now() where sale_id=p_sale_id and status='confirmed';
  insert into public.audit_events(entity_type,entity_id,action,details)
  values('sale',p_sale_id,'cancelled',jsonb_build_object('reason',p_reason,'stock_was_deducted',v_sale.stock_deducted,'restored_units',v_restored,'released_reservations',v_released,'gift_product_id',v_sale.gift_product_id));
  return p_sale_id;
end;
$$;

revoke all on function public.cancel_sale(uuid,text) from public, anon;
grant execute on function public.cancel_sale(uuid,text) to authenticated, service_role;
