create or replace view public.fitness_stock_operational with (security_invoker=true) as
select s.*,v.minimum_stock,v.reorder_target,v.default_supplier_id,fs.name default_supplier_name,greatest(v.minimum_stock-s.available_quantity,0)::integer quantity_below_minimum,greatest(greatest(v.reorder_target,v.minimum_stock)-s.available_quantity-s.incoming_quantity,0)::integer suggested_reorder_quantity,case when not s.product_active or not s.variant_active then 'inactive' when s.available_quantity<=0 and s.incoming_quantity>0 then 'incoming' when s.available_quantity<=0 then 'out_of_stock' when s.available_quantity<=v.minimum_stock then 'low_stock' else 'available' end operational_status from public.fitness_stock_overview s join public.fitness_variants v on v.id=s.variant_id left join public.fitness_suppliers fs on fs.id=v.default_supplier_id;
create or replace view public.fitness_product_catalog_v2 with (security_invoker=true) as
select p.id,p.name,p.category,p.description,p.image_url,p.active,count(v.id)::integer variant_count,coalesce(sum(s.physical_quantity),0)::integer physical_quantity,coalesce(sum(s.reserved_quantity),0)::integer reserved_quantity,coalesce(sum(s.available_quantity),0)::integer available_quantity,coalesce(sum(s.incoming_quantity),0)::integer incoming_quantity,min(v.sale_price)::numeric(12,2) min_sale_price,max(v.sale_price)::numeric(12,2) max_sale_price,count(*) filter(where s.operational_status in ('out_of_stock','low_stock'))::integer attention_variants,p.updated_at from public.fitness_products p left join public.fitness_variants v on v.product_id=p.id left join public.fitness_stock_operational s on s.variant_id=v.id group by p.id;
create or replace view public.fitness_customer_overview with (security_invoker=true) as
select c.id,c.name,c.phone,c.instagram,c.city,c.source,c.notes,c.active,c.created_at,c.updated_at,count(s.id) filter(where s.general_status<>'cancelled')::integer total_purchases,coalesce(sum(s.total_amount) filter(where s.general_status<>'cancelled'),0)::numeric(12,2) total_spent,max(coalesce(s.delivered_on,s.quoted_on)) filter(where s.general_status<>'cancelled') last_purchase_on,case when max(coalesce(s.delivered_on,s.quoted_on)) filter(where s.general_status<>'cancelled') is null then null else ((now() at time zone 'America/Sao_Paulo')::date-max(coalesce(s.delivered_on,s.quoted_on)) filter(where s.general_status<>'cancelled'))::integer end days_without_purchase,case when coalesce(sum(s.total_amount) filter(where s.general_status<>'cancelled'),0)>=500 then 'Diamante' when coalesce(sum(s.total_amount) filter(where s.general_status<>'cancelled'),0)>=300 then 'Ouro' when count(s.id) filter(where s.general_status<>'cancelled')>=2 then 'Prata' else 'Bronze' end classification from public.fitness_customers c left join public.fitness_sales s on s.customer_id=c.id group by c.id;
create or replace view public.fitness_supplier_overview with (security_invoker=true) as
select s.id,s.name,s.contact_name,s.phone,s.email,s.website,s.image_url,s.notes,s.active,s.created_at,s.updated_at,count(distinct o.id)::integer order_count,count(distinct o.id) filter(where o.status in ('pending','partial'))::integer open_orders,max(o.ordered_on) last_order_on,coalesce(sum((i.quantity_ordered-i.quantity_received)) filter(where o.status in ('pending','partial')),0)::integer incoming_units from public.fitness_suppliers s left join public.fitness_purchase_orders o on o.supplier_id=s.id left join public.fitness_purchase_order_items i on i.purchase_order_id=o.id group by s.id;
create or replace view public.fitness_sales_operational with (security_invoker=true) as select b.*,s.customer_id,s.responsible,case when s.general_status='cancelled' then 'Cancelada' when s.payment_status='received' and s.delivery_status='delivered' then 'Finalizado' when s.payment_status='receivable' and s.delivery_status='delivered' then 'À Receber' when s.payment_status='received' and s.delivery_status='to_deliver' then 'À Entregar' else 'Pedido Feito' end status_label from public.fitness_sales_overview b join public.fitness_sales s on s.id=b.id;
create or replace view public.fitness_purchase_order_operational with (security_invoker=true) as select b.*,o.freight,o.expected_on,o.received_on,o.responsible,(b.order_total+o.freight)::numeric(12,2) grand_total,s.contact_name supplier_contact,s.phone supplier_phone,s.email supplier_email from public.fitness_purchase_order_summary b join public.fitness_purchase_orders o on o.id=b.id join public.fitness_suppliers s on s.id=o.supplier_id;
create or replace view public.fitness_inventory_movement_overview with (security_invoker=true) as select m.id,m.variant_id,m.movement_type,m.quantity_delta,m.sale_id,m.purchase_order_item_id,m.transfer_group_id,m.notes,m.created_at,p.id product_id,p.name product_name,p.image_url,v.size,v.color,v.sku,case m.movement_type when 'opening' then 'Saldo inicial' when 'purchase' then 'Entrada de pedido' when 'sale' then 'Venda/entrega' when 'adjustment' then 'Ajuste' when 'cancellation' then 'Estorno' when 'conversion_in' then 'Conversão - entrada' when 'conversion_out' then 'Conversão - saída' else m.movement_type end movement_label from public.fitness_inventory_movements m join public.fitness_variants v on v.id=m.variant_id join public.fitness_products p on p.id=v.product_id;
create or replace view public.fitness_dashboard_summary_v2 with (security_invoker=true) as select d.*,(select count(*)::integer from public.fitness_customers where active) active_customers,(select count(*)::integer from public.fitness_stock_operational where operational_status='low_stock') low_stock_variants,(select count(*)::integer from public.fitness_stock_operational where operational_status='out_of_stock') out_of_stock_variants from public.fitness_dashboard_summary d;
grant select on public.fitness_stock_operational,public.fitness_product_catalog_v2,public.fitness_customer_overview,public.fitness_supplier_overview,public.fitness_sales_operational,public.fitness_purchase_order_operational,public.fitness_inventory_movement_overview,public.fitness_dashboard_summary_v2 to authenticated,service_role;
