create or replace function public.central_alerts_snapshot() returns jsonb language plpgsql stable security definer set search_path=public as $$
declare v_unread integer:=0;v_pending integer:=0;v_overdue integer:=0;v_today integer:=0;v_inventory_locations integer:=0;v_inventory_products integer:=0;v_integrations integer:=0;v_media_pending integer:=0;v_partner_without_portal integer:=0;v_items jsonb:='[]'::jsonb;v_critical integer:=0;v_attention integer:=0;v_info integer:=0;
begin
  if not (public.current_user_role()='admin' or public.can_access_operation('supplements') or public.can_access_operation('fitness') or public.can_access_marketing()) then raise exception 'Acesso negado'; end if;
  select coalesce(sum(unread_count),0)::integer,count(*) filter(where status='pending')::integer into v_unread,v_pending from public.central_conversations where public.central_can_access_scope(operation_scope);
  select count(*) filter(where status in ('planned','pending') and due_at<now())::integer,count(*) filter(where status in ('planned','pending') and due_at::date=current_date)::integer into v_overdue,v_today from public.operational_tasks where public.central_can_access_scope(operation_scope);
  if public.can_access_operation('supplements') then select count(*) filter(where a.attention_type='location' and coalesce(r.review_status,'open')<>'resolved')::integer,count(*) filter(where a.attention_type='product' and coalesce(r.review_status,'open')<>'resolved')::integer into v_inventory_locations,v_inventory_products from public.inventory_workspace_attention a left join public.inventory_reconciliation_reviews r on r.attention_type=a.attention_type and r.entity_id=a.entity_id and r.issue_code=a.status; end if;
  if public.can_manage_users() or public.current_user_role()='admin' then select count(*)::integer into v_integrations from public.central_integration_health h where coalesce(h.health_status,h.status,'')<>'healthy'; select count(*)::integer into v_partner_without_portal from public.partners p where coalesce(p.active,true) and p.partner_type<>'supplier' and not exists(select 1 from public.partner_user_links l where l.partner_id=p.id and l.active=true); end if;
  select count(*)::integer into v_media_pending from public.central_media_assets m where public.central_can_access_scope(m.operation_scope) and m.description_ai is null;
  if v_overdue>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','overdue_tasks','severity','critical','category','agenda','title','Tarefas atrasadas','description',v_overdue||' tarefa(s) passaram do prazo e ainda estão abertas.','count',v_overdue,'href','/central/pendencias'));v_critical:=v_critical+1;end if;
  if v_unread>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','unread_messages','severity','critical','category','inbox','title','Mensagens não lidas','description',v_unread||' mensagem(ns) aguardando leitura.','count',v_unread,'href','/central/inbox'));v_critical:=v_critical+1;end if;
  if v_inventory_locations>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','inventory_locations','severity','critical','category','inventory','title','Pontos de estoque para conferir','description',v_inventory_locations||' local(is) exigem conferência humana.','count',v_inventory_locations,'href','/estoque/reconciliacao'));v_critical:=v_critical+1;end if;
  if v_integrations>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','integration_health','severity','critical','category','integration','title','Integrações exigindo atenção','description',v_integrations||' integração(ões) estão desconectadas, sem sincronizar ou com erro.','count',v_integrations,'href','/central/governanca'));v_critical:=v_critical+1;end if;
  if v_pending>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','pending_conversations','severity','attention','category','inbox','title','Atendimentos pendentes','description',v_pending||' conversa(s) marcadas para retorno.','count',v_pending,'href','/central/inbox?status=pending'));v_attention:=v_attention+1;end if;
  if v_inventory_products>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','inventory_products','severity','attention','category','inventory','title','Produtos em atenção','description',v_inventory_products||' produto(s) estão zerados, abaixo da meta ou exigem revisão.','count',v_inventory_products,'href','/estoque/reconciliacao'));v_attention:=v_attention+1;end if;
  if v_today>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','today_tasks','severity','info','category','agenda','title','Agenda de hoje','description',v_today||' tarefa(s) programadas para hoje.','count',v_today,'href','/central/agenda'));v_info:=v_info+1;end if;
  if v_media_pending>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','media_pending_ai','severity','info','category','media','title','Mídias aguardando classificação','description',v_media_pending||' arquivo(s) ainda não foram classificados pelo Nexus.','count',v_media_pending,'href','/central/midia?ai=pending'));v_info:=v_info+1;end if;
  if v_partner_without_portal>0 then v_items:=v_items||jsonb_build_array(jsonb_build_object('key','partner_without_portal','severity','info','category','partner','title','Parceiros sem Portal ativo','description',v_partner_without_portal||' parceiro(s) ainda não possuem acesso ativo ao Portal.','count',v_partner_without_portal,'href','/parceiros/gerencial'));v_info:=v_info+1;end if;
  return jsonb_build_object('summary',jsonb_build_object('total',v_critical+v_attention+v_info,'critical',v_critical,'attention',v_attention,'info',v_info),'items',v_items);
end;$$;
revoke all on function public.central_alerts_snapshot() from public,anon;
grant execute on function public.central_alerts_snapshot() to authenticated;
