-- Temporary isolated lab used only during validation. It never reuses production business rows.
create or replace function public.can_use_test_lab() returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.can_manage_users);
$$;
create table if not exists public.test_lab_products(id uuid primary key default gen_random_uuid(),operation text not null check(operation in ('supplements','fitness')),name text not null,category text,variant_label text,cost_price numeric(12,2) not null default 0 check(cost_price>=0),sale_price numeric(12,2) not null default 0 check(sale_price>=0),active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.test_lab_stock(product_id uuid primary key references public.test_lab_products(id) on delete cascade,quantity integer not null default 0 check(quantity>=0),updated_at timestamptz not null default now());
create table if not exists public.test_lab_customers(id uuid primary key default gen_random_uuid(),operation text not null check(operation in ('supplements','fitness')),name text not null,phone text,created_at timestamptz not null default now());
create table if not exists public.test_lab_suppliers(id uuid primary key default gen_random_uuid(),operation text not null check(operation in ('supplements','fitness')),name text not null,created_at timestamptz not null default now());
create table if not exists public.test_lab_sales(id uuid primary key default gen_random_uuid(),operation text not null check(operation in ('supplements','fitness')),customer_id uuid not null references public.test_lab_customers(id) on delete restrict,quoted_on date not null default current_date,general_status text not null default 'active' check(general_status in ('active','finalized','cancelled')),payment_status text not null default 'receivable' check(payment_status in ('receivable','received')),delivery_status text not null default 'to_deliver' check(delivery_status in ('to_deliver','delivered')),total_cost numeric(12,2) not null default 0,total_amount numeric(12,2) not null default 0,total_profit numeric(12,2) not null default 0,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.test_lab_sale_items(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.test_lab_sales(id) on delete cascade,product_id uuid not null references public.test_lab_products(id) on delete restrict,quantity integer not null check(quantity>0),unit_cost numeric(12,2) not null,unit_price numeric(12,2) not null);
create table if not exists public.test_lab_reservations(id uuid primary key default gen_random_uuid(),sale_id uuid not null references public.test_lab_sales(id) on delete cascade,sale_item_id uuid not null unique references public.test_lab_sale_items(id) on delete cascade,product_id uuid not null references public.test_lab_products(id) on delete restrict,quantity_requested integer not null check(quantity_requested>0),quantity_reserved integer not null default 0 check(quantity_reserved>=0 and quantity_reserved<=quantity_requested),status text not null check(status in ('reserved','partial','awaiting_stock','fulfilled','cancelled')),updated_at timestamptz not null default now());
create table if not exists public.test_lab_purchase_orders(id uuid primary key default gen_random_uuid(),operation text not null check(operation in ('supplements','fitness')),supplier_id uuid not null references public.test_lab_suppliers(id) on delete restrict,ordered_on date not null default current_date,status text not null default 'pending' check(status in ('pending','partial','received','cancelled')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.test_lab_purchase_order_items(id uuid primary key default gen_random_uuid(),purchase_order_id uuid not null references public.test_lab_purchase_orders(id) on delete cascade,product_id uuid not null references public.test_lab_products(id) on delete restrict,quantity_ordered integer not null check(quantity_ordered>0),quantity_received integer not null default 0 check(quantity_received>=0 and quantity_received<=quantity_ordered),unit_cost numeric(12,2) not null default 0 check(unit_cost>=0));
create table if not exists public.test_lab_inventory_movements(id uuid primary key default gen_random_uuid(),operation text not null check(operation in ('supplements','fitness')),product_id uuid not null references public.test_lab_products(id) on delete restrict,sale_id uuid references public.test_lab_sales(id) on delete set null,purchase_order_item_id uuid references public.test_lab_purchase_order_items(id) on delete set null,movement_type text not null,quantity_delta integer not null check(quantity_delta<>0),notes text,created_at timestamptz not null default now());
create table if not exists public.test_lab_audit_events(id bigint generated always as identity primary key,operation text not null check(operation in ('supplements','fitness')),entity_type text not null,entity_id uuid,action text not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create or replace function public.test_lab_apply_inventory_movement() returns trigger language plpgsql security definer set search_path=public as $$ declare v_current integer; begin insert into public.test_lab_stock(product_id,quantity) values(new.product_id,0) on conflict(product_id) do nothing; select quantity into v_current from public.test_lab_stock where product_id=new.product_id for update; if v_current+new.quantity_delta<0 then raise exception 'Estoque de teste insuficiente. Atual: %, movimento: %',v_current,new.quantity_delta; end if; update public.test_lab_stock set quantity=quantity+new.quantity_delta,updated_at=now() where product_id=new.product_id; return new; end; $$;
drop trigger if exists trg_test_lab_inventory_movement on public.test_lab_inventory_movements;
create trigger trg_test_lab_inventory_movement after insert on public.test_lab_inventory_movements for each row execute function public.test_lab_apply_inventory_movement();
alter table public.test_lab_products enable row level security; alter table public.test_lab_stock enable row level security; alter table public.test_lab_customers enable row level security; alter table public.test_lab_suppliers enable row level security; alter table public.test_lab_sales enable row level security; alter table public.test_lab_sale_items enable row level security; alter table public.test_lab_reservations enable row level security; alter table public.test_lab_purchase_orders enable row level security; alter table public.test_lab_purchase_order_items enable row level security; alter table public.test_lab_inventory_movements enable row level security; alter table public.test_lab_audit_events enable row level security;
DO $$ declare t text; begin foreach t in array array['test_lab_products','test_lab_stock','test_lab_customers','test_lab_suppliers','test_lab_sales','test_lab_sale_items','test_lab_reservations','test_lab_purchase_orders','test_lab_purchase_order_items','test_lab_inventory_movements','test_lab_audit_events'] loop execute format('drop policy if exists test_lab_admin_all on public.%I',t); execute format('create policy test_lab_admin_all on public.%I for all to authenticated using (public.can_use_test_lab()) with check (public.can_use_test_lab())',t); execute format('grant select,insert,update,delete on public.%I to authenticated',t); end loop; end$$;
grant usage,select on sequence public.test_lab_audit_events_id_seq to authenticated; grant execute on function public.can_use_test_lab() to authenticated;
