-- Sincroniza a evolução do módulo de custos operacionais já aplicada em produção.
-- Etiqueta: baixa na entrada do produto e capitaliza o custo médio do produto.
-- Sacola/cartão: quantidade escolhida na entrega da venda.

alter table public.operational_supplies
  add column if not exists usage_stage text not null default 'sale_delivery_manual',
  add column if not exists receipt_quantity_per_product_unit numeric(14,3) not null default 0,
  add column if not exists delivery_suggestion_mode text not null default 'none',
  add column if not exists delivery_default_quantity numeric(14,3) not null default 1,
  add column if not exists delivery_capacity_product_units numeric(14,3);

alter table public.operational_supplies drop constraint if exists operational_supplies_usage_stage_check;
alter table public.operational_supplies add constraint operational_supplies_usage_stage_check check (usage_stage in ('inventory_receipt','sale_delivery_manual','sale_delivery_auto'));
alter table public.operational_supplies drop constraint if exists operational_supplies_receipt_quantity_per_product_unit_check;
alter table public.operational_supplies add constraint operational_supplies_receipt_quantity_per_product_unit_check check (receipt_quantity_per_product_unit>=0);
alter table public.operational_supplies drop constraint if exists operational_supplies_delivery_suggestion_mode_check;
alter table public.operational_supplies add constraint operational_supplies_delivery_suggestion_mode_check check (delivery_suggestion_mode in ('none','per_sale','capacity'));
alter table public.operational_supplies drop constraint if exists operational_supplies_delivery_default_quantity_check;
alter table public.operational_supplies add constraint operational_supplies_delivery_default_quantity_check check (delivery_default_quantity>=0);
alter table public.operational_supplies drop constraint if exists operational_supplies_delivery_capacity_product_units_check;
alter table public.operational_supplies add constraint operational_supplies_delivery_capacity_product_units_check check (delivery_capacity_product_units is null or delivery_capacity_product_units>0);

update public.operational_supplies set usage_stage='inventory_receipt',receipt_quantity_per_product_unit=1,delivery_suggestion_mode='none',updated_at=now() where lower(name) like '%etiqueta%';
update public.operational_supplies set usage_stage='sale_delivery_manual',receipt_quantity_per_product_unit=0,delivery_suggestion_mode='none',updated_at=now() where lower(name) like '%sacola%';

alter table public.purchase_receipts add column if not exists receipt_operational_unit_cost numeric(14,4) not null default 0,add column if not exists effective_unit_cost numeric(14,4);
alter table public.operational_supply_movements add column if not exists product_receipt_id uuid references public.purchase_receipts(id) on delete set null;
alter table public.operational_supply_movements drop constraint if exists operational_supply_movements_movement_type_check;
alter table public.operational_supply_movements add constraint operational_supply_movements_movement_type_check check (movement_type in ('opening','purchase','sale_usage','inventory_receipt_usage','adjustment','reversal'));

create table if not exists public.sale_delivery_supply_selections(
 id uuid primary key default gen_random_uuid(),operation_scope text not null check(operation_scope in('supplements','fitness')),sale_id uuid references public.sales(id) on delete cascade,fitness_sale_id uuid references public.fitness_sales(id) on delete cascade,supply_id uuid not null references public.operational_supplies(id) on delete restrict,quantity numeric(14,3) not null default 0 check(quantity>=0),suggested_quantity numeric(14,3) not null default 0 check(suggested_quantity>=0),unit_cost_snapshot numeric(14,4) not null default 0 check(unit_cost_snapshot>=0),total_cost_snapshot numeric(14,2) not null default 0 check(total_cost_snapshot>=0),confirmed_by uuid references public.profiles(id) on delete set null default auth.uid(),confirmed_at timestamptz not null default now(),notes text,check((operation_scope='supplements' and sale_id is not null and fitness_sale_id is null)or(operation_scope='fitness' and fitness_sale_id is not null and sale_id is null)));
create unique index if not exists sale_delivery_supply_selection_supp_uidx on public.sale_delivery_supply_selections(sale_id,supply_id) where operation_scope='supplements';
create unique index if not exists sale_delivery_supply_selection_fit_uidx on public.sale_delivery_supply_selections(fitness_sale_id,supply_id) where operation_scope='fitness';
alter table public.sale_delivery_supply_selections enable row level security;
drop policy if exists sale_delivery_supply_selections_select on public.sale_delivery_supply_selections;
create policy sale_delivery_supply_selections_select on public.sale_delivery_supply_selections for select to authenticated using(public.can_manage_operational_costs());
revoke all on public.sale_delivery_supply_selections from public,anon;grant select on public.sale_delivery_supply_selections to authenticated;grant all on public.sale_delivery_supply_selections to service_role;

alter table public.sale_operational_cost_snapshot_items drop constraint if exists sale_operational_cost_snapshot_items_source_type_check;
alter table public.sale_operational_cost_snapshot_items add constraint sale_operational_cost_snapshot_items_source_type_check check(source_type in('profile','product','delivery_selection'));

create or replace function public.update_operational_supply_settings(p_supply_id uuid,p_name text,p_operation_scope text,p_unit_name text,p_min_quantity numeric,p_usage_stage text,p_receipt_quantity_per_product_unit numeric default 0,p_delivery_suggestion_mode text default 'none',p_delivery_default_quantity numeric default 1,p_delivery_capacity_product_units numeric default null,p_active boolean default true,p_notes text default null)
returns uuid language plpgsql security definer set search_path=public as $$begin if not public.can_manage_operational_costs() then raise exception 'Usuário sem permissão para editar materiais';end if;if nullif(btrim(p_name),'') is null then raise exception 'Informe o nome do material';end if;if p_operation_scope not in('shared','supplements','fitness') then raise exception 'Operação inválida';end if;if p_usage_stage not in('inventory_receipt','sale_delivery_manual','sale_delivery_auto') then raise exception 'Momento de uso inválido';end if;if p_delivery_suggestion_mode not in('none','per_sale','capacity') then raise exception 'Sugestão de entrega inválida';end if;if coalesce(p_min_quantity,0)<0 or coalesce(p_receipt_quantity_per_product_unit,0)<0 or coalesce(p_delivery_default_quantity,0)<0 then raise exception 'Quantidades não podem ser negativas';end if;if p_delivery_suggestion_mode='capacity' and coalesce(p_delivery_capacity_product_units,0)<=0 then raise exception 'Informe quantos produtos cabem por unidade do material';end if;update public.operational_supplies set name=btrim(p_name),operation_scope=p_operation_scope,unit_name=coalesce(nullif(btrim(p_unit_name),''),'unidade'),min_quantity=coalesce(p_min_quantity,0),usage_stage=p_usage_stage,receipt_quantity_per_product_unit=case when p_usage_stage='inventory_receipt' then coalesce(p_receipt_quantity_per_product_unit,0) else 0 end,delivery_suggestion_mode=case when p_usage_stage like 'sale_delivery%' then p_delivery_suggestion_mode else 'none' end,delivery_default_quantity=case when p_usage_stage like 'sale_delivery%' then coalesce(p_delivery_default_quantity,1) else 0 end,delivery_capacity_product_units=case when p_usage_stage like 'sale_delivery%' and p_delivery_suggestion_mode='capacity' then p_delivery_capacity_product_units else null end,active=coalesce(p_active,true),notes=nullif(btrim(p_notes),''),updated_by=auth.uid(),updated_at=now() where id=p_supply_id;if not found then raise exception 'Material não encontrado';end if;insert into public.audit_events(entity_type,entity_id,action,details)values('operational_supply',p_supply_id,'settings_updated',jsonb_build_object('usage_stage',p_usage_stage,'receipt_quantity_per_product_unit',p_receipt_quantity_per_product_unit,'delivery_suggestion_mode',p_delivery_suggestion_mode,'delivery_default_quantity',p_delivery_default_quantity,'delivery_capacity_product_units',p_delivery_capacity_product_units,'active',p_active));return p_supply_id;end;$$;

create or replace function public.correct_operational_supply(p_supply_id uuid,p_quantity_on_hand numeric,p_average_unit_cost numeric,p_reason text) returns uuid language plpgsql security definer set search_path=public as $$declare v_supply public.operational_supplies%rowtype;v_delta numeric(14,3);begin if not public.can_manage_operational_costs() then raise exception 'Usuário sem permissão para corrigir materiais';end if;if coalesce(p_quantity_on_hand,-1)<0 then raise exception 'A quantidade não pode ser negativa';end if;if coalesce(p_average_unit_cost,-1)<0 then raise exception 'O custo médio não pode ser negativo';end if;if nullif(btrim(p_reason),'') is null then raise exception 'Informe o motivo da correção';end if;select * into v_supply from public.operational_supplies where id=p_supply_id for update;if not found then raise exception 'Material não encontrado';end if;v_delta:=p_quantity_on_hand-v_supply.quantity_on_hand;update public.operational_supplies set quantity_on_hand=p_quantity_on_hand,average_unit_cost=p_average_unit_cost,updated_by=auth.uid(),updated_at=now() where id=p_supply_id;if v_delta<>0 then insert into public.operational_supply_movements(supply_id,movement_type,quantity_delta,unit_cost_snapshot,total_cost_snapshot,notes,idempotency_key)values(p_supply_id,'adjustment',v_delta,p_average_unit_cost,round(abs(v_delta)*p_average_unit_cost,2),'Correção manual: '||btrim(p_reason),'operational-supply:correction:'||gen_random_uuid()::text);end if;insert into public.audit_events(entity_type,entity_id,action,details)values('operational_supply',p_supply_id,'corrected',jsonb_build_object('reason',btrim(p_reason),'previous_quantity',v_supply.quantity_on_hand,'new_quantity',p_quantity_on_hand,'previous_average_unit_cost',v_supply.average_unit_cost,'new_average_unit_cost',p_average_unit_cost));return p_supply_id;end;$$;

create or replace function public.get_sale_delivery_supply_options(p_operation_scope text,p_sale_id uuid) returns jsonb language plpgsql stable security definer set search_path=public as $$declare v_units numeric(14,3):=0;v_exists boolean:=false;v_result jsonb;begin if auth.uid() is null then raise exception 'Autenticação necessária';end if;if p_operation_scope='supplements' then select exists(select 1 from public.sales where id=p_sale_id and record_type='sale'),coalesce((select sum(quantity) from public.sale_items where sale_id=p_sale_id),0) into v_exists,v_units;elsif p_operation_scope='fitness' then select exists(select 1 from public.fitness_sales where id=p_sale_id),coalesce((select sum(quantity) from public.fitness_sale_items where sale_id=p_sale_id),0) into v_exists,v_units;else raise exception 'Operação inválida';end if;if not v_exists then raise exception 'Venda não encontrada';end if;select jsonb_build_object('product_units',v_units,'items',coalesce(jsonb_agg(jsonb_build_object('supply_id',s.id,'name',s.name,'unit_name',s.unit_name,'quantity_on_hand',s.quantity_on_hand,'average_unit_cost',s.average_unit_cost,'suggested_quantity',case s.delivery_suggestion_mode when 'per_sale' then s.delivery_default_quantity when 'capacity' then ceil(v_units/s.delivery_capacity_product_units)*s.delivery_default_quantity else 0 end,'suggestion_mode',s.delivery_suggestion_mode,'capacity_product_units',s.delivery_capacity_product_units,'notes',s.notes)order by s.name),'[]'::jsonb))into v_result from public.operational_supplies s where s.active and s.usage_stage='sale_delivery_manual' and s.operation_scope in('shared',p_operation_scope);return v_result;end;$$;

create or replace function public.mark_sale_delivered_with_supplies(p_sale_id uuid,p_delivered_on date,p_supplies jsonb default '[]'::jsonb) returns uuid language plpgsql security definer set search_path=public as $$declare v_sale public.sales%rowtype;v_supply public.operational_supplies%rowtype;v_qty numeric(14,3);v_units numeric(14,3);v_suggested numeric(14,3);begin if not public.can_write() then raise exception 'Usuário sem permissão para alterar entregas';end if;if p_supplies is null or jsonb_typeof(p_supplies)<>'array' then raise exception 'Materiais da entrega inválidos';end if;select * into v_sale from public.sales where id=p_sale_id and record_type='sale' for update;if not found then raise exception 'Venda não encontrada';end if;if v_sale.delivery_status='delivered' then raise exception 'Esta venda já foi entregue';end if;if v_sale.general_status='cancelled' then raise exception 'Venda cancelada não pode ser entregue';end if;select coalesce(sum(quantity),0)::numeric(14,3) into v_units from public.sale_items where sale_id=p_sale_id;delete from public.sale_delivery_supply_selections where operation_scope='supplements' and sale_id=p_sale_id;for v_supply in select * from public.operational_supplies where active and usage_stage='sale_delivery_manual' and operation_scope in('shared','supplements') order by name loop select coalesce((select(x->>'quantity')::numeric from jsonb_array_elements(p_supplies)x where(x->>'supply_id')::uuid=v_supply.id limit 1),0)into v_qty;if v_qty<0 then raise exception 'Quantidade inválida para %',v_supply.name;end if;v_suggested:=case v_supply.delivery_suggestion_mode when'per_sale'then v_supply.delivery_default_quantity when'capacity'then ceil(v_units/v_supply.delivery_capacity_product_units)*v_supply.delivery_default_quantity else 0 end;insert into public.sale_delivery_supply_selections(operation_scope,sale_id,supply_id,quantity,suggested_quantity,unit_cost_snapshot,total_cost_snapshot,confirmed_by,notes)values('supplements',p_sale_id,v_supply.id,v_qty,v_suggested,v_supply.average_unit_cost,round(v_qty*v_supply.average_unit_cost,2),auth.uid(),case when v_qty=0 then'Material revisado e não utilizado nesta entrega'else'Material confirmado na entrega'end);end loop;perform public.mark_sale_delivered(p_sale_id,p_delivered_on);return p_sale_id;end;$$;

create or replace function public.populate_delivery_selection_snapshot_items()returns trigger language plpgsql security definer set search_path=public as $$begin if new.operation_scope='supplements'then insert into public.sale_operational_cost_snapshot_items(snapshot_id,supply_id,source_type,source_label,usage_basis,quantity,unit_cost,total_cost)select new.id,s.supply_id,'delivery_selection',os.name,'per_sale',s.quantity,s.unit_cost_snapshot,s.total_cost_snapshot from public.sale_delivery_supply_selections s join public.operational_supplies os on os.id=s.supply_id where s.operation_scope='supplements'and s.sale_id=new.sale_id and s.quantity>0;else insert into public.sale_operational_cost_snapshot_items(snapshot_id,supply_id,source_type,source_label,usage_basis,quantity,unit_cost,total_cost)select new.id,s.supply_id,'delivery_selection',os.name,'per_sale',s.quantity,s.unit_cost_snapshot,s.total_cost_snapshot from public.sale_delivery_supply_selections s join public.operational_supplies os on os.id=s.supply_id where s.operation_scope='fitness'and s.fitness_sale_id=new.fitness_sale_id and s.quantity>0;end if;return new;end;$$;
drop trigger if exists sale_cost_snapshot_delivery_items on public.sale_operational_cost_snapshots;create trigger sale_cost_snapshot_delivery_items after insert on public.sale_operational_cost_snapshots for each row execute function public.populate_delivery_selection_snapshot_items();

create or replace function public.operational_cost_rules_exist(p_operation_scope text,p_sale_id uuid)returns boolean language plpgsql stable security definer set search_path=public as $$declare v_channel text;v_profile_id uuid;begin if exists(select 1 from public.sale_delivery_supply_selections s where s.operation_scope=p_operation_scope and((p_operation_scope='supplements'and s.sale_id=p_sale_id)or(p_operation_scope='fitness'and s.fitness_sale_id=p_sale_id)))then return true;end if;if p_operation_scope='supplements'then select case when partner_id is not null then'partner'else'retail'end into v_channel from public.sales where id=p_sale_id;elsif p_operation_scope='fitness'then select case when source_consignment_id is not null then'consignment'else'retail'end into v_channel from public.fitness_sales where id=p_sale_id;else return false;end if;select id into v_profile_id from public.operational_cost_profiles where operation_scope=p_operation_scope and channel=v_channel and active and is_default limit 1;if v_profile_id is null then select id into v_profile_id from public.operational_cost_profiles where operation_scope=p_operation_scope and channel='retail'and active and is_default limit 1;end if;return exists(select 1 from public.operational_cost_profile_items i join public.operational_supplies s on s.id=i.supply_id and s.active where i.profile_id=v_profile_id and s.usage_stage='sale_delivery_auto')or exists(select 1 from public.product_operational_supply_requirements r join public.operational_supplies s on s.id=r.supply_id and s.active where r.operation_scope=p_operation_scope and r.active and s.usage_stage='sale_delivery_auto'and((p_operation_scope='supplements'and exists(select 1 from public.sale_items si where si.sale_id=p_sale_id and si.product_id=r.product_id))or(p_operation_scope='fitness'and exists(select 1 from public.fitness_sale_items fsi join public.fitness_variants fv on fv.id=fsi.variant_id where fsi.sale_id=p_sale_id and fv.product_id=r.fitness_product_id))));end;$$;

create or replace function public.capture_product_moving_average_before_receipt()returns trigger language plpgsql security definer set search_path=public as $$declare v_product_id uuid;v_current_stock numeric(14,3);v_previous_stock numeric(14,3);v_previous_cost numeric(14,4);v_receipt_material_cost numeric(14,4):=0;v_effective_unit_cost numeric(14,4);begin select poi.product_id into v_product_id from public.purchase_order_items poi where poi.id=new.purchase_order_item_id;if v_product_id is null then return new;end if;select coalesce(sum(s.average_unit_cost*s.receipt_quantity_per_product_unit),0)::numeric(14,4)into v_receipt_material_cost from public.operational_supplies s where s.active and s.usage_stage='inventory_receipt'and s.operation_scope in('shared','supplements')and s.receipt_quantity_per_product_unit>0;v_effective_unit_cost:=round(new.unit_cost+v_receipt_material_cost,4);new.receipt_operational_unit_cost:=v_receipt_material_cost;new.effective_unit_cost:=v_effective_unit_cost;select coalesce(sum(sb.quantity),0)::numeric(14,3)into v_current_stock from public.stock_balances sb where sb.product_id=v_product_id;select coalesce(p.cost_price,0)::numeric(14,4)into v_previous_cost from public.products p where p.id=v_product_id;v_previous_stock:=greatest(v_current_stock-new.quantity_received,0);new.previous_stock_quantity:=v_previous_stock;new.previous_average_unit_cost:=v_previous_cost;new.calculated_average_unit_cost:=case when v_previous_stock<=0 then v_effective_unit_cost else round((v_previous_stock*v_previous_cost+new.quantity_received*v_effective_unit_cost)/(v_previous_stock+new.quantity_received),4)end;return new;end;$$;

create or replace function public.consume_inventory_receipt_supplies_after_receipt()returns trigger language plpgsql security definer set search_path=public as $$declare v_supply public.operational_supplies%rowtype;v_quantity numeric(14,3);begin for v_supply in select * from public.operational_supplies where active and usage_stage='inventory_receipt'and operation_scope in('shared','supplements')and receipt_quantity_per_product_unit>0 order by id for update loop v_quantity:=new.quantity_received*v_supply.receipt_quantity_per_product_unit;update public.operational_supplies set quantity_on_hand=quantity_on_hand-v_quantity,updated_by=auth.uid(),updated_at=now()where id=v_supply.id;insert into public.operational_supply_movements(supply_id,movement_type,quantity_delta,unit_cost_snapshot,total_cost_snapshot,operation_scope,product_receipt_id,notes,idempotency_key)values(v_supply.id,'inventory_receipt_usage',-v_quantity,v_supply.average_unit_cost,round(v_quantity*v_supply.average_unit_cost,2),'supplements',new.id,'Material aplicado na entrada do produto em estoque','inventory-receipt:'||new.id::text||':'||v_supply.id::text)on conflict(idempotency_key)do nothing;end loop;return null;end;$$;
drop trigger if exists purchase_receipts_consume_operational_supplies on public.purchase_receipts;create trigger purchase_receipts_consume_operational_supplies after insert on public.purchase_receipts for each row execute function public.consume_inventory_receipt_supplies_after_receipt();

create or replace view public.operational_supplies_overview with(security_invoker=true)as select s.id,s.operation_scope,s.name,s.sku,s.unit_name,s.quantity_on_hand,s.average_unit_cost,s.min_quantity,s.active,s.notes,s.created_by,s.updated_by,s.created_at,s.updated_at,round(greatest(s.quantity_on_hand,0)*s.average_unit_cost,2)::numeric(14,2)stock_value,case when not s.active then'inactive'when s.quantity_on_hand<0 then'negative'when s.quantity_on_hand<=s.min_quantity then'low'else'healthy'end stock_status,coalesce((select sum(abs(m.quantity_delta))from public.operational_supply_movements m where m.supply_id=s.id and m.movement_type in('sale_usage','inventory_receipt_usage')and m.created_at>=date_trunc('month',now())),0)::numeric(14,3)consumed_this_month,(select max(r.received_on)from public.operational_supply_receipts r where r.supply_id=s.id)last_received_on,s.usage_stage,s.receipt_quantity_per_product_unit,s.delivery_suggestion_mode,s.delivery_default_quantity,s.delivery_capacity_product_units from public.operational_supplies s;

revoke all on function public.update_operational_supply_settings(uuid,text,text,text,numeric,text,numeric,text,numeric,numeric,boolean,text),public.correct_operational_supply(uuid,numeric,numeric,text),public.get_sale_delivery_supply_options(text,uuid),public.mark_sale_delivered_with_supplies(uuid,date,jsonb)from public,anon;
grant execute on function public.update_operational_supply_settings(uuid,text,text,text,numeric,text,numeric,text,numeric,numeric,boolean,text),public.correct_operational_supply(uuid,numeric,numeric,text),public.get_sale_delivery_supply_options(text,uuid),public.mark_sale_delivered_with_supplies(uuid,date,jsonb)to authenticated,service_role;
