import Link from "next/link";
import { ArrowLeft, CheckCircle2, CircleDollarSign, Gift, Handshake, KeyRound, Link2, ShieldCheck, TriangleAlert } from "lucide-react";
import { DemoBanner } from "@/components/demo-banner";
import { PageHeader } from "@/components/page-header";
import { PartnerPortalAccessManager } from "@/components/partner-portal-access-manager";
import { StatCard } from "@/components/stat-card";
import { getPartnerPortalAdminSnapshot, getPartnerPortalHealthSnapshot } from "@/lib/central-data";
import { getPartnersOverview, getUnassignedPartnershipSales } from "@/lib/data";
import { formatCurrency, formatDateOnly, formatDateTime } from "@/lib/format";

export async function PartnerManagementDashboard({companyMode=false}:{companyMode?:boolean}={}){
  const [partners,unassigned,portal,portalHealth]=await Promise.all([getPartnersOverview(),getUnassignedPartnershipSales(),getPartnerPortalAdminSnapshot(),getPartnerPortalHealthSnapshot()]);
  const active=partners.filter((p)=>p.active&&p.status!=="Pausado");const pending=partners.filter((p)=>p.settlement_pending);const sales=partners.reduce((sum,p)=>sum+p.current_cycle_sales_count,0);const revenue=partners.reduce((sum,p)=>sum+p.current_cycle_revenue,0);const incomplete=partners.filter((p)=>!p.phone||!p.city||!p.contact_name).length;
  const partnersHref=companyMode?"/company/parceiros":"/parceiros";const managementHref=companyMode?"/company/parceiros/gerencial":"/parceiros/gerencial";
  return <><DemoBanner/><PageHeader eyebrow={companyMode?"Candinho Company · Parceiros":"Parceiros"} title="Gestão da rede" description={companyMode?"Indicadores internos, acertos e vendas das parcerias.":"Indicadores internos, acessos do Portal Parceiro e vendas antigas que ainda precisam de vínculo."} action={<Link className="button ghost" href={partnersHref}><ArrowLeft size={16}/>Voltar aos parceiros</Link>}/>
    <section className="stats-grid partner-stats-grid"><StatCard href={partnersHref} label="Parceiros ativos" value={String(active.length)} note={`${partners.length} cadastrados`} icon={Handshake}/><StatCard href={partnersHref} label="Acertos pendentes" value={String(pending.length)} note="Metas ou movimentos a revisar" icon={Gift}/><StatCard href={partnersHref} label="Vendas atribuídas" value={String(sales)} note={formatCurrency(revenue)} icon={CircleDollarSign}/><StatCard href="#portal-parceiro" label="Portais ativos" value={String(portal.active_portals)} note={`${portal.without_portal_count} parceiro(s) sem login`} icon={KeyRound}/><StatCard href={managementHref} label="Vendas sem vínculo" value={String(unassigned.length)} note="Legado para revisar" icon={Link2}/><StatCard href={managementHref} label="Cadastros incompletos" value={String(incomplete)} note="Sem telefone, cidade ou contato" icon={TriangleAlert}/></section>
    <article className="panel partner-portal-health-panel"><div className="panel-head"><div><h2>Saúde do Portal Parceiro</h2><p>Diagnóstico real do login, vínculo e isolamento de permissões.</p></div><span className={`badge ${portalHealth.summary.attention?"orange":"green"}`}>{portalHealth.summary.attention?<TriangleAlert size={13}/>:<ShieldCheck size={13}/>} {portalHealth.summary.ready}/{portalHealth.summary.total} prontos</span></div><div className="table-wrap"><table className="partner-access-table"><thead><tr><th>Parceiro</th><th>Login</th><th>Vínculo</th><th>Último acesso</th><th>Diagnóstico</th></tr></thead><tbody>{portalHealth.items.map((item)=><tr key={item.partner_id}><td><strong>{item.partner_name}</strong><small>{item.contact_name??"Sem contato"}</small></td><td>{item.portal_username??item.portal_user_email??"Sem login"}</td><td>{item.portal_access_active?"Ativo":item.profile_id?"Pausado":"Não criado"}</td><td>{item.last_sign_in_at?formatDateTime(item.last_sign_in_at):"Nunca entrou"}</td><td><span className={`badge ${item.health_status==="ready"?"green":item.health_status==="paused"||item.health_status==="no_login"?"orange":"red"}`}>{item.health_status==="ready"?<CheckCircle2 size={12}/>:<TriangleAlert size={12}/>} {item.health_status==="ready"?"Pronto":item.health_status==="no_login"?"Sem login":item.health_status==="paused"?"Pausado":item.health_status==="permission_leak"?"Permissão interna indevida":item.health_status==="invalid_role"?"Perfil incorreto":"Revisar"}</span></td></tr>)}</tbody></table></div></article>
    {!companyMode ? <div id="portal-parceiro"><PartnerPortalAccessManager partners={portal.partners}/></div> : null}
    {unassigned.length>0?<article className="panel"><div className="panel-head"><div><h2>Vendas antigas sem vínculo</h2><p>Abra a venda ou o parceiro sugerido para revisar a atribuição.</p></div><strong>{unassigned.length}</strong></div><div className="table-wrap"><table className="table"><thead><tr><th>Cliente</th><th>Data</th><th>Origem</th><th>Sugestão</th><th>Valor</th></tr></thead><tbody>{unassigned.map((sale)=><tr key={sale.id}><td><Link className="table-link" href={`/vendas/${sale.id}`}>{sale.customer_name}</Link></td><td>{formatDateOnly(sale.sale_date)}</td><td>{sale.location_code}</td><td>{sale.suggested_partner_id?<Link className="table-link" href={`/parceiros/${sale.suggested_partner_id}`}>{sale.suggested_partner_name}</Link>:"—"}</td><td>{formatCurrency(sale.total_amount)}</td></tr>)}</tbody></table></div></article>:<article className="panel"><div className="empty"><Link2 size={25}/><strong>Nenhuma parceria antiga sem vínculo</strong>Todos os registros marcados como parceria já possuem parceiro associado.</div></article>}
  </>;
}

export default function PartnerManagementPage(){return <PartnerManagementDashboard/>;}
